// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/modes/decision/v1/decision.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.modes.decision.v1;

@com.google.protobuf.Generated
public interface EvaluationPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.modes.decision.v1.EvaluationPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
   * @return The proposalId.
   */
  java.lang.String getProposalId();
  /**
   * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
   * @return The bytes for proposalId.
   */
  com.google.protobuf.ByteString
      getProposalIdBytes();

  /**
   * <pre>
   * APPROVE | REVIEW | BLOCK | REJECT
   * </pre>
   *
   * <code>string recommendation = 2 [json_name = "recommendation"];</code>
   * @return The recommendation.
   */
  java.lang.String getRecommendation();
  /**
   * <pre>
   * APPROVE | REVIEW | BLOCK | REJECT
   * </pre>
   *
   * <code>string recommendation = 2 [json_name = "recommendation"];</code>
   * @return The bytes for recommendation.
   */
  com.google.protobuf.ByteString
      getRecommendationBytes();

  /**
   * <code>double confidence = 3 [json_name = "confidence"];</code>
   * @return The confidence.
   */
  double getConfidence();

  /**
   * <code>string reason = 4 [json_name = "reason"];</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4 [json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
