// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/modes/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.modes.task.v1;

/**
 * Protobuf type {@code macp.modes.task.v1.TaskRequestPayload}
 */
@com.google.protobuf.Generated
public final class TaskRequestPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:macp.modes.task.v1.TaskRequestPayload)
    TaskRequestPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TaskRequestPayload");
  }
  // Use TaskRequestPayload.newBuilder() to construct.
  private TaskRequestPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TaskRequestPayload() {
    taskId_ = "";
    title_ = "";
    instructions_ = "";
    requestedAssignee_ = "";
    input_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.macp.proto.macp.modes.task.v1.TaskProto.internal_static_macp_modes_task_v1_TaskRequestPayload_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.macp.proto.macp.modes.task.v1.TaskProto.internal_static_macp_modes_task_v1_TaskRequestPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.macp.proto.macp.modes.task.v1.TaskProto.internal_static_macp_modes_task_v1_TaskRequestPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.macp.proto.macp.modes.task.v1.TaskRequestPayload.class, io.macp.proto.macp.modes.task.v1.TaskRequestPayload.Builder.class);
  }

  public static final int TASK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUCTIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instructions_ = "";
  /**
   * <code>string instructions = 3 [json_name = "instructions"];</code>
   * @return The instructions.
   */
  @java.lang.Override
  public java.lang.String getInstructions() {
    java.lang.Object ref = instructions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instructions_ = s;
      return s;
    }
  }
  /**
   * <code>string instructions = 3 [json_name = "instructions"];</code>
   * @return The bytes for instructions.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstructionsBytes() {
    java.lang.Object ref = instructions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instructions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTED_ASSIGNEE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestedAssignee_ = "";
  /**
   * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
   * @return The requestedAssignee.
   */
  @java.lang.Override
  public java.lang.String getRequestedAssignee() {
    java.lang.Object ref = requestedAssignee_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestedAssignee_ = s;
      return s;
    }
  }
  /**
   * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
   * @return The bytes for requestedAssignee.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestedAssigneeBytes() {
    java.lang.Object ref = requestedAssignee_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestedAssignee_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString input_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes input = 5 [json_name = "input"];</code>
   * @return The input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getInput() {
    return input_;
  }

  public static final int DEADLINE_UNIX_MS_FIELD_NUMBER = 6;
  private long deadlineUnixMs_ = 0L;
  /**
   * <code>int64 deadline_unix_ms = 6 [json_name = "deadlineUnixMs"];</code>
   * @return The deadlineUnixMs.
   */
  @java.lang.Override
  public long getDeadlineUnixMs() {
    return deadlineUnixMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, taskId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instructions_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, instructions_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestedAssignee_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, requestedAssignee_);
    }
    if (!input_.isEmpty()) {
      output.writeBytes(5, input_);
    }
    if (deadlineUnixMs_ != 0L) {
      output.writeInt64(6, deadlineUnixMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, taskId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instructions_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, instructions_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestedAssignee_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, requestedAssignee_);
    }
    if (!input_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, input_);
    }
    if (deadlineUnixMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, deadlineUnixMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.macp.proto.macp.modes.task.v1.TaskRequestPayload)) {
      return super.equals(obj);
    }
    io.macp.proto.macp.modes.task.v1.TaskRequestPayload other = (io.macp.proto.macp.modes.task.v1.TaskRequestPayload) obj;

    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getInstructions()
        .equals(other.getInstructions())) return false;
    if (!getRequestedAssignee()
        .equals(other.getRequestedAssignee())) return false;
    if (!getInput()
        .equals(other.getInput())) return false;
    if (getDeadlineUnixMs()
        != other.getDeadlineUnixMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + INSTRUCTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getInstructions().hashCode();
    hash = (37 * hash) + REQUESTED_ASSIGNEE_FIELD_NUMBER;
    hash = (53 * hash) + getRequestedAssignee().hashCode();
    hash = (37 * hash) + INPUT_FIELD_NUMBER;
    hash = (53 * hash) + getInput().hashCode();
    hash = (37 * hash) + DEADLINE_UNIX_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeadlineUnixMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.macp.proto.macp.modes.task.v1.TaskRequestPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code macp.modes.task.v1.TaskRequestPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:macp.modes.task.v1.TaskRequestPayload)
      io.macp.proto.macp.modes.task.v1.TaskRequestPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.macp.proto.macp.modes.task.v1.TaskProto.internal_static_macp_modes_task_v1_TaskRequestPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.macp.proto.macp.modes.task.v1.TaskProto.internal_static_macp_modes_task_v1_TaskRequestPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.macp.proto.macp.modes.task.v1.TaskRequestPayload.class, io.macp.proto.macp.modes.task.v1.TaskRequestPayload.Builder.class);
    }

    // Construct using io.macp.proto.macp.modes.task.v1.TaskRequestPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      taskId_ = "";
      title_ = "";
      instructions_ = "";
      requestedAssignee_ = "";
      input_ = com.google.protobuf.ByteString.EMPTY;
      deadlineUnixMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.macp.proto.macp.modes.task.v1.TaskProto.internal_static_macp_modes_task_v1_TaskRequestPayload_descriptor;
    }

    @java.lang.Override
    public io.macp.proto.macp.modes.task.v1.TaskRequestPayload getDefaultInstanceForType() {
      return io.macp.proto.macp.modes.task.v1.TaskRequestPayload.getDefaultInstance();
    }

    @java.lang.Override
    public io.macp.proto.macp.modes.task.v1.TaskRequestPayload build() {
      io.macp.proto.macp.modes.task.v1.TaskRequestPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.macp.proto.macp.modes.task.v1.TaskRequestPayload buildPartial() {
      io.macp.proto.macp.modes.task.v1.TaskRequestPayload result = new io.macp.proto.macp.modes.task.v1.TaskRequestPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.macp.proto.macp.modes.task.v1.TaskRequestPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.instructions_ = instructions_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.requestedAssignee_ = requestedAssignee_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.input_ = input_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.deadlineUnixMs_ = deadlineUnixMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.macp.proto.macp.modes.task.v1.TaskRequestPayload) {
        return mergeFrom((io.macp.proto.macp.modes.task.v1.TaskRequestPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.macp.proto.macp.modes.task.v1.TaskRequestPayload other) {
      if (other == io.macp.proto.macp.modes.task.v1.TaskRequestPayload.getDefaultInstance()) return this;
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getInstructions().isEmpty()) {
        instructions_ = other.instructions_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getRequestedAssignee().isEmpty()) {
        requestedAssignee_ = other.requestedAssignee_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getInput().isEmpty()) {
        setInput(other.getInput());
      }
      if (other.getDeadlineUnixMs() != 0L) {
        setDeadlineUnixMs(other.getDeadlineUnixMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              instructions_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              requestedAssignee_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              deadlineUnixMs_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_id = 1 [json_name = "taskId"];</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_id = 1 [json_name = "taskId"];</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 1 [json_name = "taskId"];</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1 [json_name = "taskId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1 [json_name = "taskId"];</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object instructions_ = "";
    /**
     * <code>string instructions = 3 [json_name = "instructions"];</code>
     * @return The instructions.
     */
    public java.lang.String getInstructions() {
      java.lang.Object ref = instructions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instructions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instructions = 3 [json_name = "instructions"];</code>
     * @return The bytes for instructions.
     */
    public com.google.protobuf.ByteString
        getInstructionsBytes() {
      java.lang.Object ref = instructions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instructions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instructions = 3 [json_name = "instructions"];</code>
     * @param value The instructions to set.
     * @return This builder for chaining.
     */
    public Builder setInstructions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instructions_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string instructions = 3 [json_name = "instructions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInstructions() {
      instructions_ = getDefaultInstance().getInstructions();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string instructions = 3 [json_name = "instructions"];</code>
     * @param value The bytes for instructions to set.
     * @return This builder for chaining.
     */
    public Builder setInstructionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instructions_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object requestedAssignee_ = "";
    /**
     * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
     * @return The requestedAssignee.
     */
    public java.lang.String getRequestedAssignee() {
      java.lang.Object ref = requestedAssignee_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestedAssignee_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
     * @return The bytes for requestedAssignee.
     */
    public com.google.protobuf.ByteString
        getRequestedAssigneeBytes() {
      java.lang.Object ref = requestedAssignee_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestedAssignee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
     * @param value The requestedAssignee to set.
     * @return This builder for chaining.
     */
    public Builder setRequestedAssignee(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestedAssignee_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestedAssignee() {
      requestedAssignee_ = getDefaultInstance().getRequestedAssignee();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string requested_assignee = 4 [json_name = "requestedAssignee"];</code>
     * @param value The bytes for requestedAssignee to set.
     * @return This builder for chaining.
     */
    public Builder setRequestedAssigneeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestedAssignee_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString input_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes input = 5 [json_name = "input"];</code>
     * @return The input.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInput() {
      return input_;
    }
    /**
     * <code>bytes input = 5 [json_name = "input"];</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      input_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bytes input = 5 [json_name = "input"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      bitField0_ = (bitField0_ & ~0x00000010);
      input_ = getDefaultInstance().getInput();
      onChanged();
      return this;
    }

    private long deadlineUnixMs_ ;
    /**
     * <code>int64 deadline_unix_ms = 6 [json_name = "deadlineUnixMs"];</code>
     * @return The deadlineUnixMs.
     */
    @java.lang.Override
    public long getDeadlineUnixMs() {
      return deadlineUnixMs_;
    }
    /**
     * <code>int64 deadline_unix_ms = 6 [json_name = "deadlineUnixMs"];</code>
     * @param value The deadlineUnixMs to set.
     * @return This builder for chaining.
     */
    public Builder setDeadlineUnixMs(long value) {

      deadlineUnixMs_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 deadline_unix_ms = 6 [json_name = "deadlineUnixMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeadlineUnixMs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      deadlineUnixMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:macp.modes.task.v1.TaskRequestPayload)
  }

  // @@protoc_insertion_point(class_scope:macp.modes.task.v1.TaskRequestPayload)
  private static final io.macp.proto.macp.modes.task.v1.TaskRequestPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.macp.proto.macp.modes.task.v1.TaskRequestPayload();
  }

  public static io.macp.proto.macp.modes.task.v1.TaskRequestPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskRequestPayload>
      PARSER = new com.google.protobuf.AbstractParser<TaskRequestPayload>() {
    @java.lang.Override
    public TaskRequestPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TaskRequestPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskRequestPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.macp.proto.macp.modes.task.v1.TaskRequestPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

