// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/modes/task/v1/task.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.modes.task.v1;

@kotlin.jvm.JvmName("-initializetaskAcceptPayload")
public inline fun taskAcceptPayload(block: io.macp.proto.macp.modes.task.v1.TaskAcceptPayloadKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.modes.task.v1.TaskAcceptPayload =
  io.macp.proto.macp.modes.task.v1.TaskAcceptPayloadKt.Dsl._create(io.macp.proto.macp.modes.task.v1.TaskAcceptPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.modes.task.v1.TaskAcceptPayload`
 */
public object TaskAcceptPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.modes.task.v1.TaskAcceptPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.modes.task.v1.TaskAcceptPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.modes.task.v1.TaskAcceptPayload = _builder.build()

    /**
     * `string task_id = 1 [json_name = "taskId"];`
     */
    public var taskId: kotlin.String
      @kotlin.jvm.JvmName("getTaskId")
        get() = _builder.taskId
      @kotlin.jvm.JvmName("setTaskId")
        set(value) {
        _builder.taskId = value
      }
    /**
     * `string task_id = 1 [json_name = "taskId"];`
     */
    public fun clearTaskId() {
      _builder.clearTaskId()
    }

    /**
     * `string assignee = 2 [json_name = "assignee"];`
     */
    public var assignee: kotlin.String
      @kotlin.jvm.JvmName("getAssignee")
        get() = _builder.assignee
      @kotlin.jvm.JvmName("setAssignee")
        set(value) {
        _builder.assignee = value
      }
    /**
     * `string assignee = 2 [json_name = "assignee"];`
     */
    public fun clearAssignee() {
      _builder.clearAssignee()
    }

    /**
     * `string reason = 3 [json_name = "reason"];`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 3 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.modes.task.v1.TaskAcceptPayload.copy(block: `io.macp.proto.macp.modes.task.v1`.TaskAcceptPayloadKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.modes.task.v1.TaskAcceptPayload =
  `io.macp.proto.macp.modes.task.v1`.TaskAcceptPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

