// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/modes/proposal/v1/proposal.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.modes.proposal.v1;

/**
 * Protobuf type {@code macp.modes.proposal.v1.CounterProposalPayload}
 */
@com.google.protobuf.Generated
public final class CounterProposalPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:macp.modes.proposal.v1.CounterProposalPayload)
    CounterProposalPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CounterProposalPayload");
  }
  // Use CounterProposalPayload.newBuilder() to construct.
  private CounterProposalPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CounterProposalPayload() {
    proposalId_ = "";
    supersedesProposalId_ = "";
    title_ = "";
    summary_ = "";
    details_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.macp.proto.macp.modes.proposal.v1.ProposalProto.internal_static_macp_modes_proposal_v1_CounterProposalPayload_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.macp.proto.macp.modes.proposal.v1.ProposalProto.internal_static_macp_modes_proposal_v1_CounterProposalPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.macp.proto.macp.modes.proposal.v1.ProposalProto.internal_static_macp_modes_proposal_v1_CounterProposalPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.class, io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.Builder.class);
  }

  public static final int PROPOSAL_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object proposalId_ = "";
  /**
   * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
   * @return The proposalId.
   */
  @java.lang.Override
  public java.lang.String getProposalId() {
    java.lang.Object ref = proposalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proposalId_ = s;
      return s;
    }
  }
  /**
   * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
   * @return The bytes for proposalId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProposalIdBytes() {
    java.lang.Object ref = proposalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proposalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUPERSEDES_PROPOSAL_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object supersedesProposalId_ = "";
  /**
   * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
   * @return The supersedesProposalId.
   */
  @java.lang.Override
  public java.lang.String getSupersedesProposalId() {
    java.lang.Object ref = supersedesProposalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      supersedesProposalId_ = s;
      return s;
    }
  }
  /**
   * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
   * @return The bytes for supersedesProposalId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSupersedesProposalIdBytes() {
    java.lang.Object ref = supersedesProposalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      supersedesProposalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUMMARY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object summary_ = "";
  /**
   * <code>string summary = 4 [json_name = "summary"];</code>
   * @return The summary.
   */
  @java.lang.Override
  public java.lang.String getSummary() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      summary_ = s;
      return s;
    }
  }
  /**
   * <code>string summary = 4 [json_name = "summary"];</code>
   * @return The bytes for summary.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSummaryBytes() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      summary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAILS_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString details_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes details = 5 [json_name = "details"];</code>
   * @return The details.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDetails() {
    return details_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(proposalId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, proposalId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(supersedesProposalId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, supersedesProposalId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(summary_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, summary_);
    }
    if (!details_.isEmpty()) {
      output.writeBytes(5, details_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(proposalId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, proposalId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(supersedesProposalId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, supersedesProposalId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(summary_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, summary_);
    }
    if (!details_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, details_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload)) {
      return super.equals(obj);
    }
    io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload other = (io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload) obj;

    if (!getProposalId()
        .equals(other.getProposalId())) return false;
    if (!getSupersedesProposalId()
        .equals(other.getSupersedesProposalId())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getSummary()
        .equals(other.getSummary())) return false;
    if (!getDetails()
        .equals(other.getDetails())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROPOSAL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProposalId().hashCode();
    hash = (37 * hash) + SUPERSEDES_PROPOSAL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSupersedesProposalId().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
    hash = (53 * hash) + getSummary().hashCode();
    hash = (37 * hash) + DETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getDetails().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code macp.modes.proposal.v1.CounterProposalPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:macp.modes.proposal.v1.CounterProposalPayload)
      io.macp.proto.macp.modes.proposal.v1.CounterProposalPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.macp.proto.macp.modes.proposal.v1.ProposalProto.internal_static_macp_modes_proposal_v1_CounterProposalPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.macp.proto.macp.modes.proposal.v1.ProposalProto.internal_static_macp_modes_proposal_v1_CounterProposalPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.class, io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.Builder.class);
    }

    // Construct using io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      proposalId_ = "";
      supersedesProposalId_ = "";
      title_ = "";
      summary_ = "";
      details_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.macp.proto.macp.modes.proposal.v1.ProposalProto.internal_static_macp_modes_proposal_v1_CounterProposalPayload_descriptor;
    }

    @java.lang.Override
    public io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload getDefaultInstanceForType() {
      return io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.getDefaultInstance();
    }

    @java.lang.Override
    public io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload build() {
      io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload buildPartial() {
      io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload result = new io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.proposalId_ = proposalId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.supersedesProposalId_ = supersedesProposalId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.summary_ = summary_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.details_ = details_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload) {
        return mergeFrom((io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload other) {
      if (other == io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload.getDefaultInstance()) return this;
      if (!other.getProposalId().isEmpty()) {
        proposalId_ = other.proposalId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSupersedesProposalId().isEmpty()) {
        supersedesProposalId_ = other.supersedesProposalId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSummary().isEmpty()) {
        summary_ = other.summary_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDetails().isEmpty()) {
        setDetails(other.getDetails());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              proposalId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              supersedesProposalId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              summary_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              details_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object proposalId_ = "";
    /**
     * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
     * @return The proposalId.
     */
    public java.lang.String getProposalId() {
      java.lang.Object ref = proposalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proposalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
     * @return The bytes for proposalId.
     */
    public com.google.protobuf.ByteString
        getProposalIdBytes() {
      java.lang.Object ref = proposalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proposalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
     * @param value The proposalId to set.
     * @return This builder for chaining.
     */
    public Builder setProposalId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      proposalId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProposalId() {
      proposalId_ = getDefaultInstance().getProposalId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string proposal_id = 1 [json_name = "proposalId"];</code>
     * @param value The bytes for proposalId to set.
     * @return This builder for chaining.
     */
    public Builder setProposalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      proposalId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object supersedesProposalId_ = "";
    /**
     * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
     * @return The supersedesProposalId.
     */
    public java.lang.String getSupersedesProposalId() {
      java.lang.Object ref = supersedesProposalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        supersedesProposalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
     * @return The bytes for supersedesProposalId.
     */
    public com.google.protobuf.ByteString
        getSupersedesProposalIdBytes() {
      java.lang.Object ref = supersedesProposalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        supersedesProposalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
     * @param value The supersedesProposalId to set.
     * @return This builder for chaining.
     */
    public Builder setSupersedesProposalId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      supersedesProposalId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSupersedesProposalId() {
      supersedesProposalId_ = getDefaultInstance().getSupersedesProposalId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string supersedes_proposal_id = 2 [json_name = "supersedesProposalId"];</code>
     * @param value The bytes for supersedesProposalId to set.
     * @return This builder for chaining.
     */
    public Builder setSupersedesProposalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      supersedesProposalId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object summary_ = "";
    /**
     * <code>string summary = 4 [json_name = "summary"];</code>
     * @return The summary.
     */
    public java.lang.String getSummary() {
      java.lang.Object ref = summary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string summary = 4 [json_name = "summary"];</code>
     * @return The bytes for summary.
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string summary = 4 [json_name = "summary"];</code>
     * @param value The summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummary(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      summary_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string summary = 4 [json_name = "summary"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSummary() {
      summary_ = getDefaultInstance().getSummary();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string summary = 4 [json_name = "summary"];</code>
     * @param value The bytes for summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      summary_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString details_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes details = 5 [json_name = "details"];</code>
     * @return The details.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDetails() {
      return details_;
    }
    /**
     * <code>bytes details = 5 [json_name = "details"];</code>
     * @param value The details to set.
     * @return This builder for chaining.
     */
    public Builder setDetails(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      details_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bytes details = 5 [json_name = "details"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDetails() {
      bitField0_ = (bitField0_ & ~0x00000010);
      details_ = getDefaultInstance().getDetails();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:macp.modes.proposal.v1.CounterProposalPayload)
  }

  // @@protoc_insertion_point(class_scope:macp.modes.proposal.v1.CounterProposalPayload)
  private static final io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload();
  }

  public static io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CounterProposalPayload>
      PARSER = new com.google.protobuf.AbstractParser<CounterProposalPayload>() {
    @java.lang.Override
    public CounterProposalPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CounterProposalPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CounterProposalPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.macp.proto.macp.modes.proposal.v1.CounterProposalPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

