// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializecapabilities")
public inline fun capabilities(block: io.macp.proto.macp.v1.CapabilitiesKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.Capabilities =
  io.macp.proto.macp.v1.CapabilitiesKt.Dsl._create(io.macp.proto.macp.v1.Capabilities.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.Capabilities`
 */
public object CapabilitiesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.Capabilities.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.Capabilities.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.Capabilities = _builder.build()

    /**
     * `.macp.v1.SessionsCapability sessions = 1 [json_name = "sessions"];`
     */
    public var sessions: io.macp.proto.macp.v1.SessionsCapability
      @kotlin.jvm.JvmName("getSessions")
        get() = _builder.sessions
      @kotlin.jvm.JvmName("setSessions")
        set(value) {
        _builder.sessions = value
      }
    /**
     * `.macp.v1.SessionsCapability sessions = 1 [json_name = "sessions"];`
     */
    public fun clearSessions() {
      _builder.clearSessions()
    }
    /**
     * `.macp.v1.SessionsCapability sessions = 1 [json_name = "sessions"];`
     * @return Whether the sessions field is set.
     */
    public fun hasSessions(): kotlin.Boolean {
      return _builder.hasSessions()
    }

    public val CapabilitiesKt.Dsl.sessionsOrNull: io.macp.proto.macp.v1.SessionsCapability?
      get() = _builder.sessionsOrNull

    /**
     * `.macp.v1.CancellationCapability cancellation = 2 [json_name = "cancellation"];`
     */
    public var cancellation: io.macp.proto.macp.v1.CancellationCapability
      @kotlin.jvm.JvmName("getCancellation")
        get() = _builder.cancellation
      @kotlin.jvm.JvmName("setCancellation")
        set(value) {
        _builder.cancellation = value
      }
    /**
     * `.macp.v1.CancellationCapability cancellation = 2 [json_name = "cancellation"];`
     */
    public fun clearCancellation() {
      _builder.clearCancellation()
    }
    /**
     * `.macp.v1.CancellationCapability cancellation = 2 [json_name = "cancellation"];`
     * @return Whether the cancellation field is set.
     */
    public fun hasCancellation(): kotlin.Boolean {
      return _builder.hasCancellation()
    }

    public val CapabilitiesKt.Dsl.cancellationOrNull: io.macp.proto.macp.v1.CancellationCapability?
      get() = _builder.cancellationOrNull

    /**
     * `.macp.v1.ProgressCapability progress = 3 [json_name = "progress"];`
     */
    public var progress: io.macp.proto.macp.v1.ProgressCapability
      @kotlin.jvm.JvmName("getProgress")
        get() = _builder.progress
      @kotlin.jvm.JvmName("setProgress")
        set(value) {
        _builder.progress = value
      }
    /**
     * `.macp.v1.ProgressCapability progress = 3 [json_name = "progress"];`
     */
    public fun clearProgress() {
      _builder.clearProgress()
    }
    /**
     * `.macp.v1.ProgressCapability progress = 3 [json_name = "progress"];`
     * @return Whether the progress field is set.
     */
    public fun hasProgress(): kotlin.Boolean {
      return _builder.hasProgress()
    }

    public val CapabilitiesKt.Dsl.progressOrNull: io.macp.proto.macp.v1.ProgressCapability?
      get() = _builder.progressOrNull

    /**
     * `.macp.v1.ManifestCapability manifest = 4 [json_name = "manifest"];`
     */
    public var manifest: io.macp.proto.macp.v1.ManifestCapability
      @kotlin.jvm.JvmName("getManifest")
        get() = _builder.manifest
      @kotlin.jvm.JvmName("setManifest")
        set(value) {
        _builder.manifest = value
      }
    /**
     * `.macp.v1.ManifestCapability manifest = 4 [json_name = "manifest"];`
     */
    public fun clearManifest() {
      _builder.clearManifest()
    }
    /**
     * `.macp.v1.ManifestCapability manifest = 4 [json_name = "manifest"];`
     * @return Whether the manifest field is set.
     */
    public fun hasManifest(): kotlin.Boolean {
      return _builder.hasManifest()
    }

    public val CapabilitiesKt.Dsl.manifestOrNull: io.macp.proto.macp.v1.ManifestCapability?
      get() = _builder.manifestOrNull

    /**
     * `.macp.v1.ModeRegistryCapability mode_registry = 5 [json_name = "modeRegistry"];`
     */
    public var modeRegistry: io.macp.proto.macp.v1.ModeRegistryCapability
      @kotlin.jvm.JvmName("getModeRegistry")
        get() = _builder.modeRegistry
      @kotlin.jvm.JvmName("setModeRegistry")
        set(value) {
        _builder.modeRegistry = value
      }
    /**
     * `.macp.v1.ModeRegistryCapability mode_registry = 5 [json_name = "modeRegistry"];`
     */
    public fun clearModeRegistry() {
      _builder.clearModeRegistry()
    }
    /**
     * `.macp.v1.ModeRegistryCapability mode_registry = 5 [json_name = "modeRegistry"];`
     * @return Whether the modeRegistry field is set.
     */
    public fun hasModeRegistry(): kotlin.Boolean {
      return _builder.hasModeRegistry()
    }

    public val CapabilitiesKt.Dsl.modeRegistryOrNull: io.macp.proto.macp.v1.ModeRegistryCapability?
      get() = _builder.modeRegistryOrNull

    /**
     * `.macp.v1.RootsCapability roots = 6 [json_name = "roots"];`
     */
    public var roots: io.macp.proto.macp.v1.RootsCapability
      @kotlin.jvm.JvmName("getRoots")
        get() = _builder.roots
      @kotlin.jvm.JvmName("setRoots")
        set(value) {
        _builder.roots = value
      }
    /**
     * `.macp.v1.RootsCapability roots = 6 [json_name = "roots"];`
     */
    public fun clearRoots() {
      _builder.clearRoots()
    }
    /**
     * `.macp.v1.RootsCapability roots = 6 [json_name = "roots"];`
     * @return Whether the roots field is set.
     */
    public fun hasRoots(): kotlin.Boolean {
      return _builder.hasRoots()
    }

    public val CapabilitiesKt.Dsl.rootsOrNull: io.macp.proto.macp.v1.RootsCapability?
      get() = _builder.rootsOrNull

    /**
     * `.macp.v1.PolicyRegistryCapability policy_registry = 7 [json_name = "policyRegistry"];`
     */
    public var policyRegistry: io.macp.proto.macp.v1.PolicyRegistryCapability
      @kotlin.jvm.JvmName("getPolicyRegistry")
        get() = _builder.policyRegistry
      @kotlin.jvm.JvmName("setPolicyRegistry")
        set(value) {
        _builder.policyRegistry = value
      }
    /**
     * `.macp.v1.PolicyRegistryCapability policy_registry = 7 [json_name = "policyRegistry"];`
     */
    public fun clearPolicyRegistry() {
      _builder.clearPolicyRegistry()
    }
    /**
     * `.macp.v1.PolicyRegistryCapability policy_registry = 7 [json_name = "policyRegistry"];`
     * @return Whether the policyRegistry field is set.
     */
    public fun hasPolicyRegistry(): kotlin.Boolean {
      return _builder.hasPolicyRegistry()
    }

    public val CapabilitiesKt.Dsl.policyRegistryOrNull: io.macp.proto.macp.v1.PolicyRegistryCapability?
      get() = _builder.policyRegistryOrNull

    /**
     * `.macp.v1.ExperimentalCapabilities experimental = 100 [json_name = "experimental"];`
     */
    public var experimental: io.macp.proto.macp.v1.ExperimentalCapabilities
      @kotlin.jvm.JvmName("getExperimental")
        get() = _builder.experimental
      @kotlin.jvm.JvmName("setExperimental")
        set(value) {
        _builder.experimental = value
      }
    /**
     * `.macp.v1.ExperimentalCapabilities experimental = 100 [json_name = "experimental"];`
     */
    public fun clearExperimental() {
      _builder.clearExperimental()
    }
    /**
     * `.macp.v1.ExperimentalCapabilities experimental = 100 [json_name = "experimental"];`
     * @return Whether the experimental field is set.
     */
    public fun hasExperimental(): kotlin.Boolean {
      return _builder.hasExperimental()
    }

    public val CapabilitiesKt.Dsl.experimentalOrNull: io.macp.proto.macp.v1.ExperimentalCapabilities?
      get() = _builder.experimentalOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.Capabilities.copy(block: `io.macp.proto.macp.v1`.CapabilitiesKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.Capabilities =
  `io.macp.proto.macp.v1`.CapabilitiesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.sessionsOrNull: io.macp.proto.macp.v1.SessionsCapability?
  get() = if (hasSessions()) getSessions() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.cancellationOrNull: io.macp.proto.macp.v1.CancellationCapability?
  get() = if (hasCancellation()) getCancellation() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.progressOrNull: io.macp.proto.macp.v1.ProgressCapability?
  get() = if (hasProgress()) getProgress() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.manifestOrNull: io.macp.proto.macp.v1.ManifestCapability?
  get() = if (hasManifest()) getManifest() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.modeRegistryOrNull: io.macp.proto.macp.v1.ModeRegistryCapability?
  get() = if (hasModeRegistry()) getModeRegistry() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.rootsOrNull: io.macp.proto.macp.v1.RootsCapability?
  get() = if (hasRoots()) getRoots() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.policyRegistryOrNull: io.macp.proto.macp.v1.PolicyRegistryCapability?
  get() = if (hasPolicyRegistry()) getPolicyRegistry() else null

public val io.macp.proto.macp.v1.CapabilitiesOrBuilder.experimentalOrNull: io.macp.proto.macp.v1.ExperimentalCapabilities?
  get() = if (hasExperimental()) getExperimental() else null

