// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/policy.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializegetPolicyRequest")
public inline fun getPolicyRequest(block: io.macp.proto.macp.v1.GetPolicyRequestKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.GetPolicyRequest =
  io.macp.proto.macp.v1.GetPolicyRequestKt.Dsl._create(io.macp.proto.macp.v1.GetPolicyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.GetPolicyRequest`
 */
public object GetPolicyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.GetPolicyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.GetPolicyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.GetPolicyRequest = _builder.build()

    /**
     * `string policy_id = 1 [json_name = "policyId"];`
     */
    public var policyId: kotlin.String
      @kotlin.jvm.JvmName("getPolicyId")
        get() = _builder.policyId
      @kotlin.jvm.JvmName("setPolicyId")
        set(value) {
        _builder.policyId = value
      }
    /**
     * `string policy_id = 1 [json_name = "policyId"];`
     */
    public fun clearPolicyId() {
      _builder.clearPolicyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.GetPolicyRequest.copy(block: `io.macp.proto.macp.v1`.GetPolicyRequestKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.GetPolicyRequest =
  `io.macp.proto.macp.v1`.GetPolicyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

