// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializelistExtModesResponse")
public inline fun listExtModesResponse(block: io.macp.proto.macp.v1.ListExtModesResponseKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.ListExtModesResponse =
  io.macp.proto.macp.v1.ListExtModesResponseKt.Dsl._create(io.macp.proto.macp.v1.ListExtModesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.ListExtModesResponse`
 */
public object ListExtModesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.ListExtModesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.ListExtModesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.ListExtModesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ModesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     */
     public val modes: com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.modesList
      )
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     * @param value The modes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addModes")
    public fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>.add(value: io.macp.proto.macp.v1.ModeDescriptor) {
      _builder.addModes(value)
    }
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     * @param value The modes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignModes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>.plusAssign(value: io.macp.proto.macp.v1.ModeDescriptor) {
      add(value)
    }
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     * @param values The modes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllModes")
    public fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>.addAll(values: kotlin.collections.Iterable<io.macp.proto.macp.v1.ModeDescriptor>) {
      _builder.addAllModes(values)
    }
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     * @param values The modes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllModes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>.plusAssign(values: kotlin.collections.Iterable<io.macp.proto.macp.v1.ModeDescriptor>) {
      addAll(values)
    }
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     * @param index The index to set the value at.
     * @param value The modes to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setModes")
    public operator fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>.set(index: kotlin.Int, value: io.macp.proto.macp.v1.ModeDescriptor) {
      _builder.setModes(index, value)
    }
    /**
     * `repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearModes")
    public fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.ModeDescriptor, ModesProxy>.clear() {
      _builder.clearModes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.ListExtModesResponse.copy(block: `io.macp.proto.macp.v1`.ListExtModesResponseKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.ListExtModesResponse =
  `io.macp.proto.macp.v1`.ListExtModesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

