// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/policy.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializepolicyRegistryCapability")
public inline fun policyRegistryCapability(block: io.macp.proto.macp.v1.PolicyRegistryCapabilityKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.PolicyRegistryCapability =
  io.macp.proto.macp.v1.PolicyRegistryCapabilityKt.Dsl._create(io.macp.proto.macp.v1.PolicyRegistryCapability.newBuilder()).apply { block() }._build()
/**
 * ```
 * Policy registry capability advertised during Initialize.
 * ```
 *
 * Protobuf type `macp.v1.PolicyRegistryCapability`
 */
public object PolicyRegistryCapabilityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.PolicyRegistryCapability.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.PolicyRegistryCapability.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.PolicyRegistryCapability = _builder.build()

    /**
     * `bool register_policy = 1 [json_name = "registerPolicy"];`
     */
    public var registerPolicy: kotlin.Boolean
      @kotlin.jvm.JvmName("getRegisterPolicy")
        get() = _builder.registerPolicy
      @kotlin.jvm.JvmName("setRegisterPolicy")
        set(value) {
        _builder.registerPolicy = value
      }
    /**
     * `bool register_policy = 1 [json_name = "registerPolicy"];`
     */
    public fun clearRegisterPolicy() {
      _builder.clearRegisterPolicy()
    }

    /**
     * `bool list_policies = 2 [json_name = "listPolicies"];`
     */
    public var listPolicies: kotlin.Boolean
      @kotlin.jvm.JvmName("getListPolicies")
        get() = _builder.listPolicies
      @kotlin.jvm.JvmName("setListPolicies")
        set(value) {
        _builder.listPolicies = value
      }
    /**
     * `bool list_policies = 2 [json_name = "listPolicies"];`
     */
    public fun clearListPolicies() {
      _builder.clearListPolicies()
    }

    /**
     * `bool list_changed = 3 [json_name = "listChanged"];`
     */
    public var listChanged: kotlin.Boolean
      @kotlin.jvm.JvmName("getListChanged")
        get() = _builder.listChanged
      @kotlin.jvm.JvmName("setListChanged")
        set(value) {
        _builder.listChanged = value
      }
    /**
     * `bool list_changed = 3 [json_name = "listChanged"];`
     */
    public fun clearListChanged() {
      _builder.clearListChanged()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.PolicyRegistryCapability.copy(block: `io.macp.proto.macp.v1`.PolicyRegistryCapabilityKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.PolicyRegistryCapability =
  `io.macp.proto.macp.v1`.PolicyRegistryCapabilityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

