// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializeprogressCapability")
public inline fun progressCapability(block: io.macp.proto.macp.v1.ProgressCapabilityKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.ProgressCapability =
  io.macp.proto.macp.v1.ProgressCapabilityKt.Dsl._create(io.macp.proto.macp.v1.ProgressCapability.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.ProgressCapability`
 */
public object ProgressCapabilityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.ProgressCapability.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.ProgressCapability.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.ProgressCapability = _builder.build()

    /**
     * `bool progress = 1 [json_name = "progress"];`
     */
    public var progress: kotlin.Boolean
      @kotlin.jvm.JvmName("getProgress")
        get() = _builder.progress
      @kotlin.jvm.JvmName("setProgress")
        set(value) {
        _builder.progress = value
      }
    /**
     * `bool progress = 1 [json_name = "progress"];`
     */
    public fun clearProgress() {
      _builder.clearProgress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.ProgressCapability.copy(block: `io.macp.proto.macp.v1`.ProgressCapabilityKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.ProgressCapability =
  `io.macp.proto.macp.v1`.ProgressCapabilityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

