// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializepromoteModeRequest")
public inline fun promoteModeRequest(block: io.macp.proto.macp.v1.PromoteModeRequestKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.PromoteModeRequest =
  io.macp.proto.macp.v1.PromoteModeRequestKt.Dsl._create(io.macp.proto.macp.v1.PromoteModeRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.PromoteModeRequest`
 */
public object PromoteModeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.PromoteModeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.PromoteModeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.PromoteModeRequest = _builder.build()

    /**
     * `string mode = 1 [json_name = "mode"];`
     */
    public var mode: kotlin.String
      @kotlin.jvm.JvmName("getMode")
        get() = _builder.mode
      @kotlin.jvm.JvmName("setMode")
        set(value) {
        _builder.mode = value
      }
    /**
     * `string mode = 1 [json_name = "mode"];`
     */
    public fun clearMode() {
      _builder.clearMode()
    }

    /**
     * ```
     * Optional new identifier for the promoted mode (e.g., "macp.mode.foo.v1").
     * If empty, the existing identifier is kept.
     * ```
     *
     * `string promoted_mode_name = 2 [json_name = "promotedModeName"];`
     */
    public var promotedModeName: kotlin.String
      @kotlin.jvm.JvmName("getPromotedModeName")
        get() = _builder.promotedModeName
      @kotlin.jvm.JvmName("setPromotedModeName")
        set(value) {
        _builder.promotedModeName = value
      }
    /**
     * ```
     * Optional new identifier for the promoted mode (e.g., "macp.mode.foo.v1").
     * If empty, the existing identifier is kept.
     * ```
     *
     * `string promoted_mode_name = 2 [json_name = "promotedModeName"];`
     */
    public fun clearPromotedModeName() {
      _builder.clearPromotedModeName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.PromoteModeRequest.copy(block: `io.macp.proto.macp.v1`.PromoteModeRequestKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.PromoteModeRequest =
  `io.macp.proto.macp.v1`.PromoteModeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

