// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializeregistryChanged")
public inline fun registryChanged(block: io.macp.proto.macp.v1.RegistryChangedKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.RegistryChanged =
  io.macp.proto.macp.v1.RegistryChangedKt.Dsl._create(io.macp.proto.macp.v1.RegistryChanged.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.RegistryChanged`
 */
public object RegistryChangedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.RegistryChanged.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.RegistryChanged.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.RegistryChanged = _builder.build()

    /**
     * `string registry = 1 [json_name = "registry"];`
     */
    public var registry: kotlin.String
      @kotlin.jvm.JvmName("getRegistry")
        get() = _builder.registry
      @kotlin.jvm.JvmName("setRegistry")
        set(value) {
        _builder.registry = value
      }
    /**
     * `string registry = 1 [json_name = "registry"];`
     */
    public fun clearRegistry() {
      _builder.clearRegistry()
    }

    /**
     * `int64 observed_at_unix_ms = 2 [json_name = "observedAtUnixMs"];`
     */
    public var observedAtUnixMs: kotlin.Long
      @kotlin.jvm.JvmName("getObservedAtUnixMs")
        get() = _builder.observedAtUnixMs
      @kotlin.jvm.JvmName("setObservedAtUnixMs")
        set(value) {
        _builder.observedAtUnixMs = value
      }
    /**
     * `int64 observed_at_unix_ms = 2 [json_name = "observedAtUnixMs"];`
     */
    public fun clearObservedAtUnixMs() {
      _builder.clearObservedAtUnixMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.RegistryChanged.copy(block: `io.macp.proto.macp.v1`.RegistryChangedKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.RegistryChanged =
  `io.macp.proto.macp.v1`.RegistryChangedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

