// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializetransportEndpoint")
public inline fun transportEndpoint(block: io.macp.proto.macp.v1.TransportEndpointKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.TransportEndpoint =
  io.macp.proto.macp.v1.TransportEndpointKt.Dsl._create(io.macp.proto.macp.v1.TransportEndpoint.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.TransportEndpoint`
 */
public object TransportEndpointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.TransportEndpoint.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.TransportEndpoint.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.TransportEndpoint = _builder.build()

    /**
     * `string transport = 1 [json_name = "transport"];`
     */
    public var transport: kotlin.String
      @kotlin.jvm.JvmName("getTransport")
        get() = _builder.transport
      @kotlin.jvm.JvmName("setTransport")
        set(value) {
        _builder.transport = value
      }
    /**
     * `string transport = 1 [json_name = "transport"];`
     */
    public fun clearTransport() {
      _builder.clearTransport()
    }

    /**
     * `string uri = 2 [json_name = "uri"];`
     */
    public var uri: kotlin.String
      @kotlin.jvm.JvmName("getUri")
        get() = _builder.uri
      @kotlin.jvm.JvmName("setUri")
        set(value) {
        _builder.uri = value
      }
    /**
     * `string uri = 2 [json_name = "uri"];`
     */
    public fun clearUri() {
      _builder.clearUri()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContentTypesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     * @return A list containing the contentTypes.
     */
    public val contentTypes: com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.contentTypesList
      )
    /**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     * @param value The contentTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addContentTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>.add(value: kotlin.String) {
      _builder.addContentTypes(value)
    }
    /**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     * @param value The contentTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignContentTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     * @param values The contentTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllContentTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllContentTypes(values)
    }
    /**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     * @param values The contentTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllContentTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     * @param index The index to set the value at.
     * @param value The contentTypes to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setContentTypes")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setContentTypes(index, value)
    }/**
     * `repeated string content_types = 3 [json_name = "contentTypes"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setContentTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTypesProxy>.clear() {
      _builder.clearContentTypes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MetadataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> metadata = 4 [json_name = "metadata"];`
     */
     public val metadata: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getMetadataMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.metadataMap
      )
    /**
     * `map<string, string> metadata = 4 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmName("putMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putMetadata(key, value)
       }
    /**
     * `map<string, string> metadata = 4 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMetadata")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> metadata = 4 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .remove(key: kotlin.String) {
         _builder.removeMetadata(key)
       }
    /**
     * `map<string, string> metadata = 4 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllMetadata(map)
       }
    /**
     * `map<string, string> metadata = 4 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .clear() {
         _builder.clearMetadata()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.TransportEndpoint.copy(block: `io.macp.proto.macp.v1`.TransportEndpointKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.TransportEndpoint =
  `io.macp.proto.macp.v1`.TransportEndpointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

