// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/policy.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializewatchPoliciesResponse")
public inline fun watchPoliciesResponse(block: io.macp.proto.macp.v1.WatchPoliciesResponseKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.WatchPoliciesResponse =
  io.macp.proto.macp.v1.WatchPoliciesResponseKt.Dsl._create(io.macp.proto.macp.v1.WatchPoliciesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.WatchPoliciesResponse`
 */
public object WatchPoliciesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.WatchPoliciesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.WatchPoliciesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.WatchPoliciesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DescriptorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     */
     public val descriptors: com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.descriptorsList
      )
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     * @param value The descriptors to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDescriptors")
    public fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>.add(value: io.macp.proto.macp.v1.PolicyDescriptor) {
      _builder.addDescriptors(value)
    }
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     * @param value The descriptors to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDescriptors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>.plusAssign(value: io.macp.proto.macp.v1.PolicyDescriptor) {
      add(value)
    }
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     * @param values The descriptors to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDescriptors")
    public fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>.addAll(values: kotlin.collections.Iterable<io.macp.proto.macp.v1.PolicyDescriptor>) {
      _builder.addAllDescriptors(values)
    }
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     * @param values The descriptors to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDescriptors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>.plusAssign(values: kotlin.collections.Iterable<io.macp.proto.macp.v1.PolicyDescriptor>) {
      addAll(values)
    }
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     * @param index The index to set the value at.
     * @param value The descriptors to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDescriptors")
    public operator fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>.set(index: kotlin.Int, value: io.macp.proto.macp.v1.PolicyDescriptor) {
      _builder.setDescriptors(index, value)
    }
    /**
     * `repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDescriptors")
    public fun com.google.protobuf.kotlin.DslList<io.macp.proto.macp.v1.PolicyDescriptor, DescriptorsProxy>.clear() {
      _builder.clearDescriptors()
    }

    /**
     * `uint64 observed_at_unix_ms = 2 [json_name = "observedAtUnixMs"];`
     */
    public var observedAtUnixMs: kotlin.Long
      @kotlin.jvm.JvmName("getObservedAtUnixMs")
        get() = _builder.observedAtUnixMs
      @kotlin.jvm.JvmName("setObservedAtUnixMs")
        set(value) {
        _builder.observedAtUnixMs = value
      }
    /**
     * `uint64 observed_at_unix_ms = 2 [json_name = "observedAtUnixMs"];`
     */
    public fun clearObservedAtUnixMs() {
      _builder.clearObservedAtUnixMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.WatchPoliciesResponse.copy(block: `io.macp.proto.macp.v1`.WatchPoliciesResponseKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.WatchPoliciesResponse =
  `io.macp.proto.macp.v1`.WatchPoliciesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

