// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.macp.proto.macp.v1;

@kotlin.jvm.JvmName("-initializewatchRootsRequest")
public inline fun watchRootsRequest(block: io.macp.proto.macp.v1.WatchRootsRequestKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.WatchRootsRequest =
  io.macp.proto.macp.v1.WatchRootsRequestKt.Dsl._create(io.macp.proto.macp.v1.WatchRootsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `macp.v1.WatchRootsRequest`
 */
public object WatchRootsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.macp.proto.macp.v1.WatchRootsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.macp.proto.macp.v1.WatchRootsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.macp.proto.macp.v1.WatchRootsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.macp.proto.macp.v1.WatchRootsRequest.copy(block: `io.macp.proto.macp.v1`.WatchRootsRequestKt.Dsl.() -> kotlin.Unit): io.macp.proto.macp.v1.WatchRootsRequest =
  `io.macp.proto.macp.v1`.WatchRootsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

