// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/modes/quorum/v1/quorum.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.modes.quorum.v1;

@com.google.protobuf.Generated
public interface ApprovePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.modes.quorum.v1.ApprovePayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1 [json_name = "requestId"];</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string reason = 2 [json_name = "reason"];</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2 [json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
