// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/modes/quorum/v1/quorum.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.modes.quorum.v1;

@com.google.protobuf.Generated
public final class QuorumProto extends com.google.protobuf.GeneratedFile {
  private QuorumProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "QuorumProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_macp_modes_quorum_v1_ApprovalRequestPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_macp_modes_quorum_v1_ApprovalRequestPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_macp_modes_quorum_v1_ApprovePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_macp_modes_quorum_v1_ApprovePayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_macp_modes_quorum_v1_RejectPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_macp_modes_quorum_v1_RejectPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_macp_modes_quorum_v1_AbstainPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_macp_modes_quorum_v1_AbstainPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!macp/modes/quorum/v1/quorum.proto\022\024mac" +
      "p.modes.quorum.v1\"\262\001\n\026ApprovalRequestPay" +
      "load\022\035\n\nrequest_id\030\001 \001(\tR\trequestId\022\026\n\006a" +
      "ction\030\002 \001(\tR\006action\022\030\n\007summary\030\003 \001(\tR\007su" +
      "mmary\022\030\n\007details\030\004 \001(\014R\007details\022-\n\022requi" +
      "red_approvals\030\005 \001(\rR\021requiredApprovals\"G" +
      "\n\016ApprovePayload\022\035\n\nrequest_id\030\001 \001(\tR\tre" +
      "questId\022\026\n\006reason\030\002 \001(\tR\006reason\"F\n\rRejec" +
      "tPayload\022\035\n\nrequest_id\030\001 \001(\tR\trequestId\022" +
      "\026\n\006reason\030\002 \001(\tR\006reason\"G\n\016AbstainPayloa" +
      "d\022\035\n\nrequest_id\030\001 \001(\tR\trequestId\022\026\n\006reas" +
      "on\030\002 \001(\tR\006reasonB\244\001\n\"io.macp.proto.macp." +
      "modes.quorum.v1B\013QuorumProtoP\001\242\002\003MMQ\252\002\024M" +
      "acp.Modes.Quorum.V1\312\002\024Macp\\Modes\\Quorum\\" +
      "V1\342\002 Macp\\Modes\\Quorum\\V1\\GPBMetadata\352\002\027" +
      "Macp::Modes::Quorum::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_macp_modes_quorum_v1_ApprovalRequestPayload_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_macp_modes_quorum_v1_ApprovalRequestPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_macp_modes_quorum_v1_ApprovalRequestPayload_descriptor,
        new java.lang.String[] { "RequestId", "Action", "Summary", "Details", "RequiredApprovals", });
    internal_static_macp_modes_quorum_v1_ApprovePayload_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_macp_modes_quorum_v1_ApprovePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_macp_modes_quorum_v1_ApprovePayload_descriptor,
        new java.lang.String[] { "RequestId", "Reason", });
    internal_static_macp_modes_quorum_v1_RejectPayload_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_macp_modes_quorum_v1_RejectPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_macp_modes_quorum_v1_RejectPayload_descriptor,
        new java.lang.String[] { "RequestId", "Reason", });
    internal_static_macp_modes_quorum_v1_AbstainPayload_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_macp_modes_quorum_v1_AbstainPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_macp_modes_quorum_v1_AbstainPayload_descriptor,
        new java.lang.String[] { "RequestId", "Reason", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
