// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

/**
 * Protobuf type {@code macp.v1.ListModesResponse}
 */
@com.google.protobuf.Generated
public final class ListModesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:macp.v1.ListModesResponse)
    ListModesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListModesResponse");
  }
  // Use ListModesResponse.newBuilder() to construct.
  private ListModesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListModesResponse() {
    modes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ListModesResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ListModesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ListModesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.macp.proto.macp.v1.ListModesResponse.class, io.macp.proto.macp.v1.ListModesResponse.Builder.class);
  }

  public static final int MODES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.macp.proto.macp.v1.ModeDescriptor> modes_;
  /**
   * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
   */
  @java.lang.Override
  public java.util.List<io.macp.proto.macp.v1.ModeDescriptor> getModesList() {
    return modes_;
  }
  /**
   * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.macp.proto.macp.v1.ModeDescriptorOrBuilder> 
      getModesOrBuilderList() {
    return modes_;
  }
  /**
   * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
   */
  @java.lang.Override
  public int getModesCount() {
    return modes_.size();
  }
  /**
   * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
   */
  @java.lang.Override
  public io.macp.proto.macp.v1.ModeDescriptor getModes(int index) {
    return modes_.get(index);
  }
  /**
   * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
   */
  @java.lang.Override
  public io.macp.proto.macp.v1.ModeDescriptorOrBuilder getModesOrBuilder(
      int index) {
    return modes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < modes_.size(); i++) {
      output.writeMessage(1, modes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = modes_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(modes_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.macp.proto.macp.v1.ListModesResponse)) {
      return super.equals(obj);
    }
    io.macp.proto.macp.v1.ListModesResponse other = (io.macp.proto.macp.v1.ListModesResponse) obj;

    if (!getModesList()
        .equals(other.getModesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getModesCount() > 0) {
      hash = (37 * hash) + MODES_FIELD_NUMBER;
      hash = (53 * hash) + getModesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.macp.proto.macp.v1.ListModesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.macp.proto.macp.v1.ListModesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.ListModesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.macp.proto.macp.v1.ListModesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code macp.v1.ListModesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:macp.v1.ListModesResponse)
      io.macp.proto.macp.v1.ListModesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ListModesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ListModesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.macp.proto.macp.v1.ListModesResponse.class, io.macp.proto.macp.v1.ListModesResponse.Builder.class);
    }

    // Construct using io.macp.proto.macp.v1.ListModesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (modesBuilder_ == null) {
        modes_ = java.util.Collections.emptyList();
      } else {
        modes_ = null;
        modesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ListModesResponse_descriptor;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.ListModesResponse getDefaultInstanceForType() {
      return io.macp.proto.macp.v1.ListModesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.ListModesResponse build() {
      io.macp.proto.macp.v1.ListModesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.ListModesResponse buildPartial() {
      io.macp.proto.macp.v1.ListModesResponse result = new io.macp.proto.macp.v1.ListModesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.macp.proto.macp.v1.ListModesResponse result) {
      if (modesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          modes_ = java.util.Collections.unmodifiableList(modes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.modes_ = modes_;
      } else {
        result.modes_ = modesBuilder_.build();
      }
    }

    private void buildPartial0(io.macp.proto.macp.v1.ListModesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.macp.proto.macp.v1.ListModesResponse) {
        return mergeFrom((io.macp.proto.macp.v1.ListModesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.macp.proto.macp.v1.ListModesResponse other) {
      if (other == io.macp.proto.macp.v1.ListModesResponse.getDefaultInstance()) return this;
      if (modesBuilder_ == null) {
        if (!other.modes_.isEmpty()) {
          if (modes_.isEmpty()) {
            modes_ = other.modes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureModesIsMutable();
            modes_.addAll(other.modes_);
          }
          onChanged();
        }
      } else {
        if (!other.modes_.isEmpty()) {
          if (modesBuilder_.isEmpty()) {
            modesBuilder_.dispose();
            modesBuilder_ = null;
            modes_ = other.modes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            modesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetModesFieldBuilder() : null;
          } else {
            modesBuilder_.addAllMessages(other.modes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.macp.proto.macp.v1.ModeDescriptor m =
                  input.readMessage(
                      io.macp.proto.macp.v1.ModeDescriptor.parser(),
                      extensionRegistry);
              if (modesBuilder_ == null) {
                ensureModesIsMutable();
                modes_.add(m);
              } else {
                modesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.macp.proto.macp.v1.ModeDescriptor> modes_ =
      java.util.Collections.emptyList();
    private void ensureModesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        modes_ = new java.util.ArrayList<io.macp.proto.macp.v1.ModeDescriptor>(modes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.macp.proto.macp.v1.ModeDescriptor, io.macp.proto.macp.v1.ModeDescriptor.Builder, io.macp.proto.macp.v1.ModeDescriptorOrBuilder> modesBuilder_;

    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public java.util.List<io.macp.proto.macp.v1.ModeDescriptor> getModesList() {
      if (modesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(modes_);
      } else {
        return modesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public int getModesCount() {
      if (modesBuilder_ == null) {
        return modes_.size();
      } else {
        return modesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public io.macp.proto.macp.v1.ModeDescriptor getModes(int index) {
      if (modesBuilder_ == null) {
        return modes_.get(index);
      } else {
        return modesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder setModes(
        int index, io.macp.proto.macp.v1.ModeDescriptor value) {
      if (modesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModesIsMutable();
        modes_.set(index, value);
        onChanged();
      } else {
        modesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder setModes(
        int index, io.macp.proto.macp.v1.ModeDescriptor.Builder builderForValue) {
      if (modesBuilder_ == null) {
        ensureModesIsMutable();
        modes_.set(index, builderForValue.build());
        onChanged();
      } else {
        modesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder addModes(io.macp.proto.macp.v1.ModeDescriptor value) {
      if (modesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModesIsMutable();
        modes_.add(value);
        onChanged();
      } else {
        modesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder addModes(
        int index, io.macp.proto.macp.v1.ModeDescriptor value) {
      if (modesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModesIsMutable();
        modes_.add(index, value);
        onChanged();
      } else {
        modesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder addModes(
        io.macp.proto.macp.v1.ModeDescriptor.Builder builderForValue) {
      if (modesBuilder_ == null) {
        ensureModesIsMutable();
        modes_.add(builderForValue.build());
        onChanged();
      } else {
        modesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder addModes(
        int index, io.macp.proto.macp.v1.ModeDescriptor.Builder builderForValue) {
      if (modesBuilder_ == null) {
        ensureModesIsMutable();
        modes_.add(index, builderForValue.build());
        onChanged();
      } else {
        modesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder addAllModes(
        java.lang.Iterable<? extends io.macp.proto.macp.v1.ModeDescriptor> values) {
      if (modesBuilder_ == null) {
        ensureModesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, modes_);
        onChanged();
      } else {
        modesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder clearModes() {
      if (modesBuilder_ == null) {
        modes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        modesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public Builder removeModes(int index) {
      if (modesBuilder_ == null) {
        ensureModesIsMutable();
        modes_.remove(index);
        onChanged();
      } else {
        modesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public io.macp.proto.macp.v1.ModeDescriptor.Builder getModesBuilder(
        int index) {
      return internalGetModesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public io.macp.proto.macp.v1.ModeDescriptorOrBuilder getModesOrBuilder(
        int index) {
      if (modesBuilder_ == null) {
        return modes_.get(index);  } else {
        return modesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public java.util.List<? extends io.macp.proto.macp.v1.ModeDescriptorOrBuilder> 
         getModesOrBuilderList() {
      if (modesBuilder_ != null) {
        return modesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(modes_);
      }
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public io.macp.proto.macp.v1.ModeDescriptor.Builder addModesBuilder() {
      return internalGetModesFieldBuilder().addBuilder(
          io.macp.proto.macp.v1.ModeDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public io.macp.proto.macp.v1.ModeDescriptor.Builder addModesBuilder(
        int index) {
      return internalGetModesFieldBuilder().addBuilder(
          index, io.macp.proto.macp.v1.ModeDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .macp.v1.ModeDescriptor modes = 1 [json_name = "modes"];</code>
     */
    public java.util.List<io.macp.proto.macp.v1.ModeDescriptor.Builder> 
         getModesBuilderList() {
      return internalGetModesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.macp.proto.macp.v1.ModeDescriptor, io.macp.proto.macp.v1.ModeDescriptor.Builder, io.macp.proto.macp.v1.ModeDescriptorOrBuilder> 
        internalGetModesFieldBuilder() {
      if (modesBuilder_ == null) {
        modesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.macp.proto.macp.v1.ModeDescriptor, io.macp.proto.macp.v1.ModeDescriptor.Builder, io.macp.proto.macp.v1.ModeDescriptorOrBuilder>(
                modes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        modes_ = null;
      }
      return modesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:macp.v1.ListModesResponse)
  }

  // @@protoc_insertion_point(class_scope:macp.v1.ListModesResponse)
  private static final io.macp.proto.macp.v1.ListModesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.macp.proto.macp.v1.ListModesResponse();
  }

  public static io.macp.proto.macp.v1.ListModesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListModesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListModesResponse>() {
    @java.lang.Override
    public ListModesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListModesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListModesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.macp.proto.macp.v1.ListModesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

