// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/policy.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

@com.google.protobuf.Generated
public interface ListPoliciesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.v1.ListPoliciesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];</code>
   */
  java.util.List<io.macp.proto.macp.v1.PolicyDescriptor> 
      getDescriptorsList();
  /**
   * <code>repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];</code>
   */
  io.macp.proto.macp.v1.PolicyDescriptor getDescriptors(int index);
  /**
   * <code>repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];</code>
   */
  int getDescriptorsCount();
  /**
   * <code>repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];</code>
   */
  java.util.List<? extends io.macp.proto.macp.v1.PolicyDescriptorOrBuilder> 
      getDescriptorsOrBuilderList();
  /**
   * <code>repeated .macp.v1.PolicyDescriptor descriptors = 1 [json_name = "descriptors"];</code>
   */
  io.macp.proto.macp.v1.PolicyDescriptorOrBuilder getDescriptorsOrBuilder(
      int index);
}
