// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

@com.google.protobuf.Generated
public interface ManifestCapabilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.v1.ManifestCapability)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool get_manifest = 1 [json_name = "getManifest"];</code>
   * @return The getManifest.
   */
  boolean getGetManifest();
}
