// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

/**
 * Protobuf type {@code macp.v1.ModeDescriptor}
 */
@com.google.protobuf.Generated
public final class ModeDescriptor extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:macp.v1.ModeDescriptor)
    ModeDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ModeDescriptor");
  }
  // Use ModeDescriptor.newBuilder() to construct.
  private ModeDescriptor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ModeDescriptor() {
    mode_ = "";
    modeVersion_ = "";
    title_ = "";
    description_ = "";
    determinismClass_ = "";
    participantModel_ = "";
    messageTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    terminalMessageTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 9:
        return internalGetSchemaUris();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.macp.proto.macp.v1.ModeDescriptor.class, io.macp.proto.macp.v1.ModeDescriptor.Builder.class);
  }

  public static final int MODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mode_ = "";
  /**
   * <code>string mode = 1 [json_name = "mode"];</code>
   * @return The mode.
   */
  @java.lang.Override
  public java.lang.String getMode() {
    java.lang.Object ref = mode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mode_ = s;
      return s;
    }
  }
  /**
   * <code>string mode = 1 [json_name = "mode"];</code>
   * @return The bytes for mode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModeBytes() {
    java.lang.Object ref = mode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODE_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modeVersion_ = "";
  /**
   * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
   * @return The modeVersion.
   */
  @java.lang.Override
  public java.lang.String getModeVersion() {
    java.lang.Object ref = modeVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modeVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
   * @return The bytes for modeVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModeVersionBytes() {
    java.lang.Object ref = modeVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modeVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETERMINISM_CLASS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object determinismClass_ = "";
  /**
   * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
   * @return The determinismClass.
   */
  @java.lang.Override
  public java.lang.String getDeterminismClass() {
    java.lang.Object ref = determinismClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      determinismClass_ = s;
      return s;
    }
  }
  /**
   * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
   * @return The bytes for determinismClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeterminismClassBytes() {
    java.lang.Object ref = determinismClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      determinismClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTICIPANT_MODEL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object participantModel_ = "";
  /**
   * <code>string participant_model = 6 [json_name = "participantModel"];</code>
   * @return The participantModel.
   */
  @java.lang.Override
  public java.lang.String getParticipantModel() {
    java.lang.Object ref = participantModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      participantModel_ = s;
      return s;
    }
  }
  /**
   * <code>string participant_model = 6 [json_name = "participantModel"];</code>
   * @return The bytes for participantModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParticipantModelBytes() {
    java.lang.Object ref = participantModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      participantModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_TYPES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList messageTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @return A list containing the messageTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getMessageTypesList() {
    return messageTypes_;
  }
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @return The count of messageTypes.
   */
  public int getMessageTypesCount() {
    return messageTypes_.size();
  }
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @param index The index of the element to return.
   * @return The messageTypes at the given index.
   */
  public java.lang.String getMessageTypes(int index) {
    return messageTypes_.get(index);
  }
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the messageTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getMessageTypesBytes(int index) {
    return messageTypes_.getByteString(index);
  }

  public static final int TERMINAL_MESSAGE_TYPES_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList terminalMessageTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @return A list containing the terminalMessageTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getTerminalMessageTypesList() {
    return terminalMessageTypes_;
  }
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @return The count of terminalMessageTypes.
   */
  public int getTerminalMessageTypesCount() {
    return terminalMessageTypes_.size();
  }
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @param index The index of the element to return.
   * @return The terminalMessageTypes at the given index.
   */
  public java.lang.String getTerminalMessageTypes(int index) {
    return terminalMessageTypes_.get(index);
  }
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the terminalMessageTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getTerminalMessageTypesBytes(int index) {
    return terminalMessageTypes_.getByteString(index);
  }

  public static final int SCHEMA_URIS_FIELD_NUMBER = 9;
  private static final class SchemaUrisDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_SchemaUrisEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> schemaUris_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetSchemaUris() {
    if (schemaUris_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SchemaUrisDefaultEntryHolder.defaultEntry);
    }
    return schemaUris_;
  }
  public int getSchemaUrisCount() {
    return internalGetSchemaUris().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  @java.lang.Override
  public boolean containsSchemaUris(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetSchemaUris().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSchemaUrisMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getSchemaUris() {
    return getSchemaUrisMap();
  }
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getSchemaUrisMap() {
    return internalGetSchemaUris().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getSchemaUrisOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSchemaUris().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  @java.lang.Override
  public java.lang.String getSchemaUrisOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSchemaUris().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, mode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modeVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, modeVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(determinismClass_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, determinismClass_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(participantModel_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, participantModel_);
    }
    for (int i = 0; i < messageTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, messageTypes_.getRaw(i));
    }
    for (int i = 0; i < terminalMessageTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, terminalMessageTypes_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetSchemaUris(),
        SchemaUrisDefaultEntryHolder.defaultEntry,
        9);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, mode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modeVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, modeVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(determinismClass_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, determinismClass_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(participantModel_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, participantModel_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < messageTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(messageTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMessageTypesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < terminalMessageTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(terminalMessageTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTerminalMessageTypesList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetSchemaUris().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      schemaUris__ = SchemaUrisDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, schemaUris__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.macp.proto.macp.v1.ModeDescriptor)) {
      return super.equals(obj);
    }
    io.macp.proto.macp.v1.ModeDescriptor other = (io.macp.proto.macp.v1.ModeDescriptor) obj;

    if (!getMode()
        .equals(other.getMode())) return false;
    if (!getModeVersion()
        .equals(other.getModeVersion())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getDeterminismClass()
        .equals(other.getDeterminismClass())) return false;
    if (!getParticipantModel()
        .equals(other.getParticipantModel())) return false;
    if (!getMessageTypesList()
        .equals(other.getMessageTypesList())) return false;
    if (!getTerminalMessageTypesList()
        .equals(other.getTerminalMessageTypesList())) return false;
    if (!internalGetSchemaUris().equals(
        other.internalGetSchemaUris())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode().hashCode();
    hash = (37 * hash) + MODE_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModeVersion().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + DETERMINISM_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getDeterminismClass().hashCode();
    hash = (37 * hash) + PARTICIPANT_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getParticipantModel().hashCode();
    if (getMessageTypesCount() > 0) {
      hash = (37 * hash) + MESSAGE_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getMessageTypesList().hashCode();
    }
    if (getTerminalMessageTypesCount() > 0) {
      hash = (37 * hash) + TERMINAL_MESSAGE_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getTerminalMessageTypesList().hashCode();
    }
    if (!internalGetSchemaUris().getMap().isEmpty()) {
      hash = (37 * hash) + SCHEMA_URIS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSchemaUris().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.macp.proto.macp.v1.ModeDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.macp.proto.macp.v1.ModeDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.ModeDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.macp.proto.macp.v1.ModeDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code macp.v1.ModeDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:macp.v1.ModeDescriptor)
      io.macp.proto.macp.v1.ModeDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 9:
          return internalGetSchemaUris();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 9:
          return internalGetMutableSchemaUris();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.macp.proto.macp.v1.ModeDescriptor.class, io.macp.proto.macp.v1.ModeDescriptor.Builder.class);
    }

    // Construct using io.macp.proto.macp.v1.ModeDescriptor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mode_ = "";
      modeVersion_ = "";
      title_ = "";
      description_ = "";
      determinismClass_ = "";
      participantModel_ = "";
      messageTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      terminalMessageTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableSchemaUris().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_ModeDescriptor_descriptor;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.ModeDescriptor getDefaultInstanceForType() {
      return io.macp.proto.macp.v1.ModeDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.ModeDescriptor build() {
      io.macp.proto.macp.v1.ModeDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.ModeDescriptor buildPartial() {
      io.macp.proto.macp.v1.ModeDescriptor result = new io.macp.proto.macp.v1.ModeDescriptor(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.macp.proto.macp.v1.ModeDescriptor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.modeVersion_ = modeVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.determinismClass_ = determinismClass_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.participantModel_ = participantModel_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        messageTypes_.makeImmutable();
        result.messageTypes_ = messageTypes_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        terminalMessageTypes_.makeImmutable();
        result.terminalMessageTypes_ = terminalMessageTypes_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.schemaUris_ = internalGetSchemaUris();
        result.schemaUris_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.macp.proto.macp.v1.ModeDescriptor) {
        return mergeFrom((io.macp.proto.macp.v1.ModeDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.macp.proto.macp.v1.ModeDescriptor other) {
      if (other == io.macp.proto.macp.v1.ModeDescriptor.getDefaultInstance()) return this;
      if (!other.getMode().isEmpty()) {
        mode_ = other.mode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getModeVersion().isEmpty()) {
        modeVersion_ = other.modeVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDeterminismClass().isEmpty()) {
        determinismClass_ = other.determinismClass_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getParticipantModel().isEmpty()) {
        participantModel_ = other.participantModel_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.messageTypes_.isEmpty()) {
        if (messageTypes_.isEmpty()) {
          messageTypes_ = other.messageTypes_;
          bitField0_ |= 0x00000040;
        } else {
          ensureMessageTypesIsMutable();
          messageTypes_.addAll(other.messageTypes_);
        }
        onChanged();
      }
      if (!other.terminalMessageTypes_.isEmpty()) {
        if (terminalMessageTypes_.isEmpty()) {
          terminalMessageTypes_ = other.terminalMessageTypes_;
          bitField0_ |= 0x00000080;
        } else {
          ensureTerminalMessageTypesIsMutable();
          terminalMessageTypes_.addAll(other.terminalMessageTypes_);
        }
        onChanged();
      }
      internalGetMutableSchemaUris().mergeFrom(
          other.internalGetSchemaUris());
      bitField0_ |= 0x00000100;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              mode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              modeVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              determinismClass_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              participantModel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              ensureMessageTypesIsMutable();
              messageTypes_.add(input.readStringRequireUtf8());
              break;
            } // case 58
            case 66: {
              ensureTerminalMessageTypesIsMutable();
              terminalMessageTypes_.add(input.readStringRequireUtf8());
              break;
            } // case 66
            case 74: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              schemaUris__ = input.readMessage(
                  SchemaUrisDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableSchemaUris().getMutableMap().put(
                  schemaUris__.getKey(), schemaUris__.getValue());
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object mode_ = "";
    /**
     * <code>string mode = 1 [json_name = "mode"];</code>
     * @return The mode.
     */
    public java.lang.String getMode() {
      java.lang.Object ref = mode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mode = 1 [json_name = "mode"];</code>
     * @return The bytes for mode.
     */
    public com.google.protobuf.ByteString
        getModeBytes() {
      java.lang.Object ref = mode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mode = 1 [json_name = "mode"];</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string mode = 1 [json_name = "mode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      mode_ = getDefaultInstance().getMode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string mode = 1 [json_name = "mode"];</code>
     * @param value The bytes for mode to set.
     * @return This builder for chaining.
     */
    public Builder setModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object modeVersion_ = "";
    /**
     * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
     * @return The modeVersion.
     */
    public java.lang.String getModeVersion() {
      java.lang.Object ref = modeVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modeVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
     * @return The bytes for modeVersion.
     */
    public com.google.protobuf.ByteString
        getModeVersionBytes() {
      java.lang.Object ref = modeVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modeVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
     * @param value The modeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModeVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modeVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModeVersion() {
      modeVersion_ = getDefaultInstance().getModeVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
     * @param value The bytes for modeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModeVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modeVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object determinismClass_ = "";
    /**
     * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
     * @return The determinismClass.
     */
    public java.lang.String getDeterminismClass() {
      java.lang.Object ref = determinismClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        determinismClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
     * @return The bytes for determinismClass.
     */
    public com.google.protobuf.ByteString
        getDeterminismClassBytes() {
      java.lang.Object ref = determinismClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        determinismClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
     * @param value The determinismClass to set.
     * @return This builder for chaining.
     */
    public Builder setDeterminismClass(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      determinismClass_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeterminismClass() {
      determinismClass_ = getDefaultInstance().getDeterminismClass();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
     * @param value The bytes for determinismClass to set.
     * @return This builder for chaining.
     */
    public Builder setDeterminismClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      determinismClass_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object participantModel_ = "";
    /**
     * <code>string participant_model = 6 [json_name = "participantModel"];</code>
     * @return The participantModel.
     */
    public java.lang.String getParticipantModel() {
      java.lang.Object ref = participantModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        participantModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string participant_model = 6 [json_name = "participantModel"];</code>
     * @return The bytes for participantModel.
     */
    public com.google.protobuf.ByteString
        getParticipantModelBytes() {
      java.lang.Object ref = participantModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        participantModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string participant_model = 6 [json_name = "participantModel"];</code>
     * @param value The participantModel to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      participantModel_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string participant_model = 6 [json_name = "participantModel"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipantModel() {
      participantModel_ = getDefaultInstance().getParticipantModel();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string participant_model = 6 [json_name = "participantModel"];</code>
     * @param value The bytes for participantModel to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      participantModel_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList messageTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMessageTypesIsMutable() {
      if (!messageTypes_.isModifiable()) {
        messageTypes_ = new com.google.protobuf.LazyStringArrayList(messageTypes_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @return A list containing the messageTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getMessageTypesList() {
      messageTypes_.makeImmutable();
      return messageTypes_;
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @return The count of messageTypes.
     */
    public int getMessageTypesCount() {
      return messageTypes_.size();
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @param index The index of the element to return.
     * @return The messageTypes at the given index.
     */
    public java.lang.String getMessageTypes(int index) {
      return messageTypes_.get(index);
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the messageTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getMessageTypesBytes(int index) {
      return messageTypes_.getByteString(index);
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @param index The index to set the value at.
     * @param value The messageTypes to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMessageTypesIsMutable();
      messageTypes_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @param value The messageTypes to add.
     * @return This builder for chaining.
     */
    public Builder addMessageTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMessageTypesIsMutable();
      messageTypes_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @param values The messageTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllMessageTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureMessageTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, messageTypes_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageTypes() {
      messageTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
     * @param value The bytes of the messageTypes to add.
     * @return This builder for chaining.
     */
    public Builder addMessageTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMessageTypesIsMutable();
      messageTypes_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList terminalMessageTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTerminalMessageTypesIsMutable() {
      if (!terminalMessageTypes_.isModifiable()) {
        terminalMessageTypes_ = new com.google.protobuf.LazyStringArrayList(terminalMessageTypes_);
      }
      bitField0_ |= 0x00000080;
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @return A list containing the terminalMessageTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getTerminalMessageTypesList() {
      terminalMessageTypes_.makeImmutable();
      return terminalMessageTypes_;
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @return The count of terminalMessageTypes.
     */
    public int getTerminalMessageTypesCount() {
      return terminalMessageTypes_.size();
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @param index The index of the element to return.
     * @return The terminalMessageTypes at the given index.
     */
    public java.lang.String getTerminalMessageTypes(int index) {
      return terminalMessageTypes_.get(index);
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the terminalMessageTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getTerminalMessageTypesBytes(int index) {
      return terminalMessageTypes_.getByteString(index);
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @param index The index to set the value at.
     * @param value The terminalMessageTypes to set.
     * @return This builder for chaining.
     */
    public Builder setTerminalMessageTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTerminalMessageTypesIsMutable();
      terminalMessageTypes_.set(index, value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @param value The terminalMessageTypes to add.
     * @return This builder for chaining.
     */
    public Builder addTerminalMessageTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTerminalMessageTypesIsMutable();
      terminalMessageTypes_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @param values The terminalMessageTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllTerminalMessageTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureTerminalMessageTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, terminalMessageTypes_);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTerminalMessageTypes() {
      terminalMessageTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
     * @param value The bytes of the terminalMessageTypes to add.
     * @return This builder for chaining.
     */
    public Builder addTerminalMessageTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTerminalMessageTypesIsMutable();
      terminalMessageTypes_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> schemaUris_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetSchemaUris() {
      if (schemaUris_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SchemaUrisDefaultEntryHolder.defaultEntry);
      }
      return schemaUris_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableSchemaUris() {
      if (schemaUris_ == null) {
        schemaUris_ = com.google.protobuf.MapField.newMapField(
            SchemaUrisDefaultEntryHolder.defaultEntry);
      }
      if (!schemaUris_.isMutable()) {
        schemaUris_ = schemaUris_.copy();
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return schemaUris_;
    }
    public int getSchemaUrisCount() {
      return internalGetSchemaUris().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    @java.lang.Override
    public boolean containsSchemaUris(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSchemaUris().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSchemaUrisMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSchemaUris() {
      return getSchemaUrisMap();
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getSchemaUrisMap() {
      return internalGetSchemaUris().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getSchemaUrisOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSchemaUris().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    @java.lang.Override
    public java.lang.String getSchemaUrisOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSchemaUris().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearSchemaUris() {
      bitField0_ = (bitField0_ & ~0x00000100);
      internalGetMutableSchemaUris().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    public Builder removeSchemaUris(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableSchemaUris().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableSchemaUris() {
      bitField0_ |= 0x00000100;
      return internalGetMutableSchemaUris().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    public Builder putSchemaUris(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableSchemaUris().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
     */
    public Builder putAllSchemaUris(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableSchemaUris().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000100;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:macp.v1.ModeDescriptor)
  }

  // @@protoc_insertion_point(class_scope:macp.v1.ModeDescriptor)
  private static final io.macp.proto.macp.v1.ModeDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.macp.proto.macp.v1.ModeDescriptor();
  }

  public static io.macp.proto.macp.v1.ModeDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModeDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<ModeDescriptor>() {
    @java.lang.Override
    public ModeDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ModeDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModeDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.macp.proto.macp.v1.ModeDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

