// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

@com.google.protobuf.Generated
public interface ModeDescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.v1.ModeDescriptor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mode = 1 [json_name = "mode"];</code>
   * @return The mode.
   */
  java.lang.String getMode();
  /**
   * <code>string mode = 1 [json_name = "mode"];</code>
   * @return The bytes for mode.
   */
  com.google.protobuf.ByteString
      getModeBytes();

  /**
   * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
   * @return The modeVersion.
   */
  java.lang.String getModeVersion();
  /**
   * <code>string mode_version = 2 [json_name = "modeVersion"];</code>
   * @return The bytes for modeVersion.
   */
  com.google.protobuf.ByteString
      getModeVersionBytes();

  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
   * @return The determinismClass.
   */
  java.lang.String getDeterminismClass();
  /**
   * <code>string determinism_class = 5 [json_name = "determinismClass"];</code>
   * @return The bytes for determinismClass.
   */
  com.google.protobuf.ByteString
      getDeterminismClassBytes();

  /**
   * <code>string participant_model = 6 [json_name = "participantModel"];</code>
   * @return The participantModel.
   */
  java.lang.String getParticipantModel();
  /**
   * <code>string participant_model = 6 [json_name = "participantModel"];</code>
   * @return The bytes for participantModel.
   */
  com.google.protobuf.ByteString
      getParticipantModelBytes();

  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @return A list containing the messageTypes.
   */
  java.util.List<java.lang.String>
      getMessageTypesList();
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @return The count of messageTypes.
   */
  int getMessageTypesCount();
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @param index The index of the element to return.
   * @return The messageTypes at the given index.
   */
  java.lang.String getMessageTypes(int index);
  /**
   * <code>repeated string message_types = 7 [json_name = "messageTypes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the messageTypes at the given index.
   */
  com.google.protobuf.ByteString
      getMessageTypesBytes(int index);

  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @return A list containing the terminalMessageTypes.
   */
  java.util.List<java.lang.String>
      getTerminalMessageTypesList();
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @return The count of terminalMessageTypes.
   */
  int getTerminalMessageTypesCount();
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @param index The index of the element to return.
   * @return The terminalMessageTypes at the given index.
   */
  java.lang.String getTerminalMessageTypes(int index);
  /**
   * <code>repeated string terminal_message_types = 8 [json_name = "terminalMessageTypes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the terminalMessageTypes at the given index.
   */
  com.google.protobuf.ByteString
      getTerminalMessageTypesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  int getSchemaUrisCount();
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  boolean containsSchemaUris(
      java.lang.String key);
  /**
   * Use {@link #getSchemaUrisMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getSchemaUris();
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getSchemaUrisMap();
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  /* nullable */
java.lang.String getSchemaUrisOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; schema_uris = 9 [json_name = "schemaUris"];</code>
   */
  java.lang.String getSchemaUrisOrThrow(
      java.lang.String key);
}
