// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/policy.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

/**
 * <pre>
 * Policy registry capability advertised during Initialize.
 * </pre>
 *
 * Protobuf type {@code macp.v1.PolicyRegistryCapability}
 */
@com.google.protobuf.Generated
public final class PolicyRegistryCapability extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:macp.v1.PolicyRegistryCapability)
    PolicyRegistryCapabilityOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PolicyRegistryCapability");
  }
  // Use PolicyRegistryCapability.newBuilder() to construct.
  private PolicyRegistryCapability(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PolicyRegistryCapability() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.macp.proto.macp.v1.PolicyProto.internal_static_macp_v1_PolicyRegistryCapability_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.macp.proto.macp.v1.PolicyProto.internal_static_macp_v1_PolicyRegistryCapability_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.macp.proto.macp.v1.PolicyProto.internal_static_macp_v1_PolicyRegistryCapability_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.macp.proto.macp.v1.PolicyRegistryCapability.class, io.macp.proto.macp.v1.PolicyRegistryCapability.Builder.class);
  }

  public static final int REGISTER_POLICY_FIELD_NUMBER = 1;
  private boolean registerPolicy_ = false;
  /**
   * <code>bool register_policy = 1 [json_name = "registerPolicy"];</code>
   * @return The registerPolicy.
   */
  @java.lang.Override
  public boolean getRegisterPolicy() {
    return registerPolicy_;
  }

  public static final int LIST_POLICIES_FIELD_NUMBER = 2;
  private boolean listPolicies_ = false;
  /**
   * <code>bool list_policies = 2 [json_name = "listPolicies"];</code>
   * @return The listPolicies.
   */
  @java.lang.Override
  public boolean getListPolicies() {
    return listPolicies_;
  }

  public static final int LIST_CHANGED_FIELD_NUMBER = 3;
  private boolean listChanged_ = false;
  /**
   * <code>bool list_changed = 3 [json_name = "listChanged"];</code>
   * @return The listChanged.
   */
  @java.lang.Override
  public boolean getListChanged() {
    return listChanged_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (registerPolicy_ != false) {
      output.writeBool(1, registerPolicy_);
    }
    if (listPolicies_ != false) {
      output.writeBool(2, listPolicies_);
    }
    if (listChanged_ != false) {
      output.writeBool(3, listChanged_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (registerPolicy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, registerPolicy_);
    }
    if (listPolicies_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, listPolicies_);
    }
    if (listChanged_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, listChanged_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.macp.proto.macp.v1.PolicyRegistryCapability)) {
      return super.equals(obj);
    }
    io.macp.proto.macp.v1.PolicyRegistryCapability other = (io.macp.proto.macp.v1.PolicyRegistryCapability) obj;

    if (getRegisterPolicy()
        != other.getRegisterPolicy()) return false;
    if (getListPolicies()
        != other.getListPolicies()) return false;
    if (getListChanged()
        != other.getListChanged()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGISTER_POLICY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRegisterPolicy());
    hash = (37 * hash) + LIST_POLICIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getListPolicies());
    hash = (37 * hash) + LIST_CHANGED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getListChanged());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.PolicyRegistryCapability parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.macp.proto.macp.v1.PolicyRegistryCapability prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Policy registry capability advertised during Initialize.
   * </pre>
   *
   * Protobuf type {@code macp.v1.PolicyRegistryCapability}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:macp.v1.PolicyRegistryCapability)
      io.macp.proto.macp.v1.PolicyRegistryCapabilityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.macp.proto.macp.v1.PolicyProto.internal_static_macp_v1_PolicyRegistryCapability_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.macp.proto.macp.v1.PolicyProto.internal_static_macp_v1_PolicyRegistryCapability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.macp.proto.macp.v1.PolicyRegistryCapability.class, io.macp.proto.macp.v1.PolicyRegistryCapability.Builder.class);
    }

    // Construct using io.macp.proto.macp.v1.PolicyRegistryCapability.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      registerPolicy_ = false;
      listPolicies_ = false;
      listChanged_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.macp.proto.macp.v1.PolicyProto.internal_static_macp_v1_PolicyRegistryCapability_descriptor;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.PolicyRegistryCapability getDefaultInstanceForType() {
      return io.macp.proto.macp.v1.PolicyRegistryCapability.getDefaultInstance();
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.PolicyRegistryCapability build() {
      io.macp.proto.macp.v1.PolicyRegistryCapability result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.PolicyRegistryCapability buildPartial() {
      io.macp.proto.macp.v1.PolicyRegistryCapability result = new io.macp.proto.macp.v1.PolicyRegistryCapability(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.macp.proto.macp.v1.PolicyRegistryCapability result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.registerPolicy_ = registerPolicy_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.listPolicies_ = listPolicies_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.listChanged_ = listChanged_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.macp.proto.macp.v1.PolicyRegistryCapability) {
        return mergeFrom((io.macp.proto.macp.v1.PolicyRegistryCapability)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.macp.proto.macp.v1.PolicyRegistryCapability other) {
      if (other == io.macp.proto.macp.v1.PolicyRegistryCapability.getDefaultInstance()) return this;
      if (other.getRegisterPolicy() != false) {
        setRegisterPolicy(other.getRegisterPolicy());
      }
      if (other.getListPolicies() != false) {
        setListPolicies(other.getListPolicies());
      }
      if (other.getListChanged() != false) {
        setListChanged(other.getListChanged());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              registerPolicy_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              listPolicies_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              listChanged_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean registerPolicy_ ;
    /**
     * <code>bool register_policy = 1 [json_name = "registerPolicy"];</code>
     * @return The registerPolicy.
     */
    @java.lang.Override
    public boolean getRegisterPolicy() {
      return registerPolicy_;
    }
    /**
     * <code>bool register_policy = 1 [json_name = "registerPolicy"];</code>
     * @param value The registerPolicy to set.
     * @return This builder for chaining.
     */
    public Builder setRegisterPolicy(boolean value) {

      registerPolicy_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool register_policy = 1 [json_name = "registerPolicy"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRegisterPolicy() {
      bitField0_ = (bitField0_ & ~0x00000001);
      registerPolicy_ = false;
      onChanged();
      return this;
    }

    private boolean listPolicies_ ;
    /**
     * <code>bool list_policies = 2 [json_name = "listPolicies"];</code>
     * @return The listPolicies.
     */
    @java.lang.Override
    public boolean getListPolicies() {
      return listPolicies_;
    }
    /**
     * <code>bool list_policies = 2 [json_name = "listPolicies"];</code>
     * @param value The listPolicies to set.
     * @return This builder for chaining.
     */
    public Builder setListPolicies(boolean value) {

      listPolicies_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool list_policies = 2 [json_name = "listPolicies"];</code>
     * @return This builder for chaining.
     */
    public Builder clearListPolicies() {
      bitField0_ = (bitField0_ & ~0x00000002);
      listPolicies_ = false;
      onChanged();
      return this;
    }

    private boolean listChanged_ ;
    /**
     * <code>bool list_changed = 3 [json_name = "listChanged"];</code>
     * @return The listChanged.
     */
    @java.lang.Override
    public boolean getListChanged() {
      return listChanged_;
    }
    /**
     * <code>bool list_changed = 3 [json_name = "listChanged"];</code>
     * @param value The listChanged to set.
     * @return This builder for chaining.
     */
    public Builder setListChanged(boolean value) {

      listChanged_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool list_changed = 3 [json_name = "listChanged"];</code>
     * @return This builder for chaining.
     */
    public Builder clearListChanged() {
      bitField0_ = (bitField0_ & ~0x00000004);
      listChanged_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:macp.v1.PolicyRegistryCapability)
  }

  // @@protoc_insertion_point(class_scope:macp.v1.PolicyRegistryCapability)
  private static final io.macp.proto.macp.v1.PolicyRegistryCapability DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.macp.proto.macp.v1.PolicyRegistryCapability();
  }

  public static io.macp.proto.macp.v1.PolicyRegistryCapability getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PolicyRegistryCapability>
      PARSER = new com.google.protobuf.AbstractParser<PolicyRegistryCapability>() {
    @java.lang.Override
    public PolicyRegistryCapability parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PolicyRegistryCapability> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PolicyRegistryCapability> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.macp.proto.macp.v1.PolicyRegistryCapability getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

