// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

@com.google.protobuf.Generated
public interface RegisterExtModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.v1.RegisterExtModeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.macp.v1.ModeDescriptor descriptor = 1 [json_name = "descriptor"];</code>
   * @return Whether the descriptor field is set.
   */
  boolean hasDescriptor();
  /**
   * <code>.macp.v1.ModeDescriptor descriptor = 1 [json_name = "descriptor"];</code>
   * @return The descriptor.
   */
  io.macp.proto.macp.v1.ModeDescriptor getDescriptor();
  /**
   * <code>.macp.v1.ModeDescriptor descriptor = 1 [json_name = "descriptor"];</code>
   */
  io.macp.proto.macp.v1.ModeDescriptorOrBuilder getDescriptorOrBuilder();
}
