// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/core.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

/**
 * Protobuf type {@code macp.v1.SessionMetadata}
 */
@com.google.protobuf.Generated
public final class SessionMetadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:macp.v1.SessionMetadata)
    SessionMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "SessionMetadata");
  }
  // Use SessionMetadata.newBuilder() to construct.
  private SessionMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SessionMetadata() {
    sessionId_ = "";
    mode_ = "";
    state_ = 0;
    modeVersion_ = "";
    configurationVersion_ = "";
    policyVersion_ = "";
    participants_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    participantActivity_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_SessionMetadata_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_SessionMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_SessionMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.macp.proto.macp.v1.SessionMetadata.class, io.macp.proto.macp.v1.SessionMetadata.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mode_ = "";
  /**
   * <code>string mode = 2 [json_name = "mode"];</code>
   * @return The mode.
   */
  @java.lang.Override
  public java.lang.String getMode() {
    java.lang.Object ref = mode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mode_ = s;
      return s;
    }
  }
  /**
   * <code>string mode = 2 [json_name = "mode"];</code>
   * @return The bytes for mode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModeBytes() {
    java.lang.Object ref = mode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_FIELD_NUMBER = 3;
  private int state_ = 0;
  /**
   * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override public io.macp.proto.macp.v1.SessionState getState() {
    io.macp.proto.macp.v1.SessionState result = io.macp.proto.macp.v1.SessionState.forNumber(state_);
    return result == null ? io.macp.proto.macp.v1.SessionState.UNRECOGNIZED : result;
  }

  public static final int STARTED_AT_UNIX_MS_FIELD_NUMBER = 4;
  private long startedAtUnixMs_ = 0L;
  /**
   * <code>int64 started_at_unix_ms = 4 [json_name = "startedAtUnixMs"];</code>
   * @return The startedAtUnixMs.
   */
  @java.lang.Override
  public long getStartedAtUnixMs() {
    return startedAtUnixMs_;
  }

  public static final int EXPIRES_AT_UNIX_MS_FIELD_NUMBER = 5;
  private long expiresAtUnixMs_ = 0L;
  /**
   * <code>int64 expires_at_unix_ms = 5 [json_name = "expiresAtUnixMs"];</code>
   * @return The expiresAtUnixMs.
   */
  @java.lang.Override
  public long getExpiresAtUnixMs() {
    return expiresAtUnixMs_;
  }

  public static final int MODE_VERSION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modeVersion_ = "";
  /**
   * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
   * @return The modeVersion.
   */
  @java.lang.Override
  public java.lang.String getModeVersion() {
    java.lang.Object ref = modeVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modeVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
   * @return The bytes for modeVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModeVersionBytes() {
    java.lang.Object ref = modeVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modeVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIGURATION_VERSION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object configurationVersion_ = "";
  /**
   * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
   * @return The configurationVersion.
   */
  @java.lang.Override
  public java.lang.String getConfigurationVersion() {
    java.lang.Object ref = configurationVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configurationVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
   * @return The bytes for configurationVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigurationVersionBytes() {
    java.lang.Object ref = configurationVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configurationVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POLICY_VERSION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object policyVersion_ = "";
  /**
   * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
   * @return The policyVersion.
   */
  @java.lang.Override
  public java.lang.String getPolicyVersion() {
    java.lang.Object ref = policyVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      policyVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
   * @return The bytes for policyVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPolicyVersionBytes() {
    java.lang.Object ref = policyVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      policyVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTICIPANTS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList participants_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string participants = 9 [json_name = "participants"];</code>
   * @return A list containing the participants.
   */
  public com.google.protobuf.ProtocolStringList
      getParticipantsList() {
    return participants_;
  }
  /**
   * <code>repeated string participants = 9 [json_name = "participants"];</code>
   * @return The count of participants.
   */
  public int getParticipantsCount() {
    return participants_.size();
  }
  /**
   * <code>repeated string participants = 9 [json_name = "participants"];</code>
   * @param index The index of the element to return.
   * @return The participants at the given index.
   */
  public java.lang.String getParticipants(int index) {
    return participants_.get(index);
  }
  /**
   * <code>repeated string participants = 9 [json_name = "participants"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the participants at the given index.
   */
  public com.google.protobuf.ByteString
      getParticipantsBytes(int index) {
    return participants_.getByteString(index);
  }

  public static final int PARTICIPANT_ACTIVITY_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private java.util.List<io.macp.proto.macp.v1.ParticipantActivity> participantActivity_;
  /**
   * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
   */
  @java.lang.Override
  public java.util.List<io.macp.proto.macp.v1.ParticipantActivity> getParticipantActivityList() {
    return participantActivity_;
  }
  /**
   * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.macp.proto.macp.v1.ParticipantActivityOrBuilder> 
      getParticipantActivityOrBuilderList() {
    return participantActivity_;
  }
  /**
   * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
   */
  @java.lang.Override
  public int getParticipantActivityCount() {
    return participantActivity_.size();
  }
  /**
   * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
   */
  @java.lang.Override
  public io.macp.proto.macp.v1.ParticipantActivity getParticipantActivity(int index) {
    return participantActivity_.get(index);
  }
  /**
   * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
   */
  @java.lang.Override
  public io.macp.proto.macp.v1.ParticipantActivityOrBuilder getParticipantActivityOrBuilder(
      int index) {
    return participantActivity_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, mode_);
    }
    if (state_ != io.macp.proto.macp.v1.SessionState.SESSION_STATE_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, state_);
    }
    if (startedAtUnixMs_ != 0L) {
      output.writeInt64(4, startedAtUnixMs_);
    }
    if (expiresAtUnixMs_ != 0L) {
      output.writeInt64(5, expiresAtUnixMs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modeVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, modeVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(configurationVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, configurationVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(policyVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, policyVersion_);
    }
    for (int i = 0; i < participants_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, participants_.getRaw(i));
    }
    for (int i = 0; i < participantActivity_.size(); i++) {
      output.writeMessage(10, participantActivity_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, mode_);
    }
    if (state_ != io.macp.proto.macp.v1.SessionState.SESSION_STATE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, state_);
    }
    if (startedAtUnixMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, startedAtUnixMs_);
    }
    if (expiresAtUnixMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, expiresAtUnixMs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modeVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, modeVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(configurationVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, configurationVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(policyVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, policyVersion_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < participants_.size(); i++) {
        dataSize += computeStringSizeNoTag(participants_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParticipantsList().size();
    }

        {
          final int count = participantActivity_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(participantActivity_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.macp.proto.macp.v1.SessionMetadata)) {
      return super.equals(obj);
    }
    io.macp.proto.macp.v1.SessionMetadata other = (io.macp.proto.macp.v1.SessionMetadata) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getMode()
        .equals(other.getMode())) return false;
    if (state_ != other.state_) return false;
    if (getStartedAtUnixMs()
        != other.getStartedAtUnixMs()) return false;
    if (getExpiresAtUnixMs()
        != other.getExpiresAtUnixMs()) return false;
    if (!getModeVersion()
        .equals(other.getModeVersion())) return false;
    if (!getConfigurationVersion()
        .equals(other.getConfigurationVersion())) return false;
    if (!getPolicyVersion()
        .equals(other.getPolicyVersion())) return false;
    if (!getParticipantsList()
        .equals(other.getParticipantsList())) return false;
    if (!getParticipantActivityList()
        .equals(other.getParticipantActivityList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + STARTED_AT_UNIX_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartedAtUnixMs());
    hash = (37 * hash) + EXPIRES_AT_UNIX_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiresAtUnixMs());
    hash = (37 * hash) + MODE_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModeVersion().hashCode();
    hash = (37 * hash) + CONFIGURATION_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getConfigurationVersion().hashCode();
    hash = (37 * hash) + POLICY_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getPolicyVersion().hashCode();
    if (getParticipantsCount() > 0) {
      hash = (37 * hash) + PARTICIPANTS_FIELD_NUMBER;
      hash = (53 * hash) + getParticipantsList().hashCode();
    }
    if (getParticipantActivityCount() > 0) {
      hash = (37 * hash) + PARTICIPANT_ACTIVITY_FIELD_NUMBER;
      hash = (53 * hash) + getParticipantActivityList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.macp.proto.macp.v1.SessionMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.macp.proto.macp.v1.SessionMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.macp.proto.macp.v1.SessionMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.macp.proto.macp.v1.SessionMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code macp.v1.SessionMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:macp.v1.SessionMetadata)
      io.macp.proto.macp.v1.SessionMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_SessionMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_SessionMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.macp.proto.macp.v1.SessionMetadata.class, io.macp.proto.macp.v1.SessionMetadata.Builder.class);
    }

    // Construct using io.macp.proto.macp.v1.SessionMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      mode_ = "";
      state_ = 0;
      startedAtUnixMs_ = 0L;
      expiresAtUnixMs_ = 0L;
      modeVersion_ = "";
      configurationVersion_ = "";
      policyVersion_ = "";
      participants_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (participantActivityBuilder_ == null) {
        participantActivity_ = java.util.Collections.emptyList();
      } else {
        participantActivity_ = null;
        participantActivityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.macp.proto.macp.v1.CoreProto.internal_static_macp_v1_SessionMetadata_descriptor;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.SessionMetadata getDefaultInstanceForType() {
      return io.macp.proto.macp.v1.SessionMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.SessionMetadata build() {
      io.macp.proto.macp.v1.SessionMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.macp.proto.macp.v1.SessionMetadata buildPartial() {
      io.macp.proto.macp.v1.SessionMetadata result = new io.macp.proto.macp.v1.SessionMetadata(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.macp.proto.macp.v1.SessionMetadata result) {
      if (participantActivityBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0)) {
          participantActivity_ = java.util.Collections.unmodifiableList(participantActivity_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.participantActivity_ = participantActivity_;
      } else {
        result.participantActivity_ = participantActivityBuilder_.build();
      }
    }

    private void buildPartial0(io.macp.proto.macp.v1.SessionMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.startedAtUnixMs_ = startedAtUnixMs_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.expiresAtUnixMs_ = expiresAtUnixMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.modeVersion_ = modeVersion_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.configurationVersion_ = configurationVersion_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.policyVersion_ = policyVersion_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        participants_.makeImmutable();
        result.participants_ = participants_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.macp.proto.macp.v1.SessionMetadata) {
        return mergeFrom((io.macp.proto.macp.v1.SessionMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.macp.proto.macp.v1.SessionMetadata other) {
      if (other == io.macp.proto.macp.v1.SessionMetadata.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMode().isEmpty()) {
        mode_ = other.mode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.getStartedAtUnixMs() != 0L) {
        setStartedAtUnixMs(other.getStartedAtUnixMs());
      }
      if (other.getExpiresAtUnixMs() != 0L) {
        setExpiresAtUnixMs(other.getExpiresAtUnixMs());
      }
      if (!other.getModeVersion().isEmpty()) {
        modeVersion_ = other.modeVersion_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getConfigurationVersion().isEmpty()) {
        configurationVersion_ = other.configurationVersion_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getPolicyVersion().isEmpty()) {
        policyVersion_ = other.policyVersion_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.participants_.isEmpty()) {
        if (participants_.isEmpty()) {
          participants_ = other.participants_;
          bitField0_ |= 0x00000100;
        } else {
          ensureParticipantsIsMutable();
          participants_.addAll(other.participants_);
        }
        onChanged();
      }
      if (participantActivityBuilder_ == null) {
        if (!other.participantActivity_.isEmpty()) {
          if (participantActivity_.isEmpty()) {
            participantActivity_ = other.participantActivity_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureParticipantActivityIsMutable();
            participantActivity_.addAll(other.participantActivity_);
          }
          onChanged();
        }
      } else {
        if (!other.participantActivity_.isEmpty()) {
          if (participantActivityBuilder_.isEmpty()) {
            participantActivityBuilder_.dispose();
            participantActivityBuilder_ = null;
            participantActivity_ = other.participantActivity_;
            bitField0_ = (bitField0_ & ~0x00000200);
            participantActivityBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetParticipantActivityFieldBuilder() : null;
          } else {
            participantActivityBuilder_.addAllMessages(other.participantActivity_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              mode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              startedAtUnixMs_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              expiresAtUnixMs_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              modeVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              configurationVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              policyVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              ensureParticipantsIsMutable();
              participants_.add(input.readStringRequireUtf8());
              break;
            } // case 74
            case 82: {
              io.macp.proto.macp.v1.ParticipantActivity m =
                  input.readMessage(
                      io.macp.proto.macp.v1.ParticipantActivity.parser(),
                      extensionRegistry);
              if (participantActivityBuilder_ == null) {
                ensureParticipantActivityIsMutable();
                participantActivity_.add(m);
              } else {
                participantActivityBuilder_.addMessage(m);
              }
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object mode_ = "";
    /**
     * <code>string mode = 2 [json_name = "mode"];</code>
     * @return The mode.
     */
    public java.lang.String getMode() {
      java.lang.Object ref = mode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mode = 2 [json_name = "mode"];</code>
     * @return The bytes for mode.
     */
    public com.google.protobuf.ByteString
        getModeBytes() {
      java.lang.Object ref = mode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mode = 2 [json_name = "mode"];</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string mode = 2 [json_name = "mode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      mode_ = getDefaultInstance().getMode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string mode = 2 [json_name = "mode"];</code>
     * @param value The bytes for mode to set.
     * @return This builder for chaining.
     */
    public Builder setModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
     * @param value The enum numeric value on the wire for state to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public io.macp.proto.macp.v1.SessionState getState() {
      io.macp.proto.macp.v1.SessionState result = io.macp.proto.macp.v1.SessionState.forNumber(state_);
      return result == null ? io.macp.proto.macp.v1.SessionState.UNRECOGNIZED : result;
    }
    /**
     * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(io.macp.proto.macp.v1.SessionState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.macp.v1.SessionState state = 3 [json_name = "state"];</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000004);
      state_ = 0;
      onChanged();
      return this;
    }

    private long startedAtUnixMs_ ;
    /**
     * <code>int64 started_at_unix_ms = 4 [json_name = "startedAtUnixMs"];</code>
     * @return The startedAtUnixMs.
     */
    @java.lang.Override
    public long getStartedAtUnixMs() {
      return startedAtUnixMs_;
    }
    /**
     * <code>int64 started_at_unix_ms = 4 [json_name = "startedAtUnixMs"];</code>
     * @param value The startedAtUnixMs to set.
     * @return This builder for chaining.
     */
    public Builder setStartedAtUnixMs(long value) {

      startedAtUnixMs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 started_at_unix_ms = 4 [json_name = "startedAtUnixMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartedAtUnixMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      startedAtUnixMs_ = 0L;
      onChanged();
      return this;
    }

    private long expiresAtUnixMs_ ;
    /**
     * <code>int64 expires_at_unix_ms = 5 [json_name = "expiresAtUnixMs"];</code>
     * @return The expiresAtUnixMs.
     */
    @java.lang.Override
    public long getExpiresAtUnixMs() {
      return expiresAtUnixMs_;
    }
    /**
     * <code>int64 expires_at_unix_ms = 5 [json_name = "expiresAtUnixMs"];</code>
     * @param value The expiresAtUnixMs to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresAtUnixMs(long value) {

      expiresAtUnixMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expires_at_unix_ms = 5 [json_name = "expiresAtUnixMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresAtUnixMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      expiresAtUnixMs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object modeVersion_ = "";
    /**
     * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
     * @return The modeVersion.
     */
    public java.lang.String getModeVersion() {
      java.lang.Object ref = modeVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modeVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
     * @return The bytes for modeVersion.
     */
    public com.google.protobuf.ByteString
        getModeVersionBytes() {
      java.lang.Object ref = modeVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modeVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
     * @param value The modeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModeVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modeVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModeVersion() {
      modeVersion_ = getDefaultInstance().getModeVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string mode_version = 6 [json_name = "modeVersion"];</code>
     * @param value The bytes for modeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModeVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modeVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object configurationVersion_ = "";
    /**
     * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
     * @return The configurationVersion.
     */
    public java.lang.String getConfigurationVersion() {
      java.lang.Object ref = configurationVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configurationVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
     * @return The bytes for configurationVersion.
     */
    public com.google.protobuf.ByteString
        getConfigurationVersionBytes() {
      java.lang.Object ref = configurationVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configurationVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
     * @param value The configurationVersion to set.
     * @return This builder for chaining.
     */
    public Builder setConfigurationVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      configurationVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigurationVersion() {
      configurationVersion_ = getDefaultInstance().getConfigurationVersion();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string configuration_version = 7 [json_name = "configurationVersion"];</code>
     * @param value The bytes for configurationVersion to set.
     * @return This builder for chaining.
     */
    public Builder setConfigurationVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      configurationVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object policyVersion_ = "";
    /**
     * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
     * @return The policyVersion.
     */
    public java.lang.String getPolicyVersion() {
      java.lang.Object ref = policyVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        policyVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
     * @return The bytes for policyVersion.
     */
    public com.google.protobuf.ByteString
        getPolicyVersionBytes() {
      java.lang.Object ref = policyVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        policyVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
     * @param value The policyVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      policyVersion_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPolicyVersion() {
      policyVersion_ = getDefaultInstance().getPolicyVersion();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string policy_version = 8 [json_name = "policyVersion"];</code>
     * @param value The bytes for policyVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      policyVersion_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList participants_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureParticipantsIsMutable() {
      if (!participants_.isModifiable()) {
        participants_ = new com.google.protobuf.LazyStringArrayList(participants_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @return A list containing the participants.
     */
    public com.google.protobuf.ProtocolStringList
        getParticipantsList() {
      participants_.makeImmutable();
      return participants_;
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @return The count of participants.
     */
    public int getParticipantsCount() {
      return participants_.size();
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @param index The index of the element to return.
     * @return The participants at the given index.
     */
    public java.lang.String getParticipants(int index) {
      return participants_.get(index);
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the participants at the given index.
     */
    public com.google.protobuf.ByteString
        getParticipantsBytes(int index) {
      return participants_.getByteString(index);
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @param index The index to set the value at.
     * @param value The participants to set.
     * @return This builder for chaining.
     */
    public Builder setParticipants(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParticipantsIsMutable();
      participants_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @param value The participants to add.
     * @return This builder for chaining.
     */
    public Builder addParticipants(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParticipantsIsMutable();
      participants_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @param values The participants to add.
     * @return This builder for chaining.
     */
    public Builder addAllParticipants(
        java.lang.Iterable<java.lang.String> values) {
      ensureParticipantsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, participants_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipants() {
      participants_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participants = 9 [json_name = "participants"];</code>
     * @param value The bytes of the participants to add.
     * @return This builder for chaining.
     */
    public Builder addParticipantsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureParticipantsIsMutable();
      participants_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.util.List<io.macp.proto.macp.v1.ParticipantActivity> participantActivity_ =
      java.util.Collections.emptyList();
    private void ensureParticipantActivityIsMutable() {
      if (!((bitField0_ & 0x00000200) != 0)) {
        participantActivity_ = new java.util.ArrayList<io.macp.proto.macp.v1.ParticipantActivity>(participantActivity_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.macp.proto.macp.v1.ParticipantActivity, io.macp.proto.macp.v1.ParticipantActivity.Builder, io.macp.proto.macp.v1.ParticipantActivityOrBuilder> participantActivityBuilder_;

    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public java.util.List<io.macp.proto.macp.v1.ParticipantActivity> getParticipantActivityList() {
      if (participantActivityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(participantActivity_);
      } else {
        return participantActivityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public int getParticipantActivityCount() {
      if (participantActivityBuilder_ == null) {
        return participantActivity_.size();
      } else {
        return participantActivityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public io.macp.proto.macp.v1.ParticipantActivity getParticipantActivity(int index) {
      if (participantActivityBuilder_ == null) {
        return participantActivity_.get(index);
      } else {
        return participantActivityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder setParticipantActivity(
        int index, io.macp.proto.macp.v1.ParticipantActivity value) {
      if (participantActivityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParticipantActivityIsMutable();
        participantActivity_.set(index, value);
        onChanged();
      } else {
        participantActivityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder setParticipantActivity(
        int index, io.macp.proto.macp.v1.ParticipantActivity.Builder builderForValue) {
      if (participantActivityBuilder_ == null) {
        ensureParticipantActivityIsMutable();
        participantActivity_.set(index, builderForValue.build());
        onChanged();
      } else {
        participantActivityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder addParticipantActivity(io.macp.proto.macp.v1.ParticipantActivity value) {
      if (participantActivityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParticipantActivityIsMutable();
        participantActivity_.add(value);
        onChanged();
      } else {
        participantActivityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder addParticipantActivity(
        int index, io.macp.proto.macp.v1.ParticipantActivity value) {
      if (participantActivityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParticipantActivityIsMutable();
        participantActivity_.add(index, value);
        onChanged();
      } else {
        participantActivityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder addParticipantActivity(
        io.macp.proto.macp.v1.ParticipantActivity.Builder builderForValue) {
      if (participantActivityBuilder_ == null) {
        ensureParticipantActivityIsMutable();
        participantActivity_.add(builderForValue.build());
        onChanged();
      } else {
        participantActivityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder addParticipantActivity(
        int index, io.macp.proto.macp.v1.ParticipantActivity.Builder builderForValue) {
      if (participantActivityBuilder_ == null) {
        ensureParticipantActivityIsMutable();
        participantActivity_.add(index, builderForValue.build());
        onChanged();
      } else {
        participantActivityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder addAllParticipantActivity(
        java.lang.Iterable<? extends io.macp.proto.macp.v1.ParticipantActivity> values) {
      if (participantActivityBuilder_ == null) {
        ensureParticipantActivityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, participantActivity_);
        onChanged();
      } else {
        participantActivityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder clearParticipantActivity() {
      if (participantActivityBuilder_ == null) {
        participantActivity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        participantActivityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public Builder removeParticipantActivity(int index) {
      if (participantActivityBuilder_ == null) {
        ensureParticipantActivityIsMutable();
        participantActivity_.remove(index);
        onChanged();
      } else {
        participantActivityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public io.macp.proto.macp.v1.ParticipantActivity.Builder getParticipantActivityBuilder(
        int index) {
      return internalGetParticipantActivityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public io.macp.proto.macp.v1.ParticipantActivityOrBuilder getParticipantActivityOrBuilder(
        int index) {
      if (participantActivityBuilder_ == null) {
        return participantActivity_.get(index);  } else {
        return participantActivityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public java.util.List<? extends io.macp.proto.macp.v1.ParticipantActivityOrBuilder> 
         getParticipantActivityOrBuilderList() {
      if (participantActivityBuilder_ != null) {
        return participantActivityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(participantActivity_);
      }
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public io.macp.proto.macp.v1.ParticipantActivity.Builder addParticipantActivityBuilder() {
      return internalGetParticipantActivityFieldBuilder().addBuilder(
          io.macp.proto.macp.v1.ParticipantActivity.getDefaultInstance());
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public io.macp.proto.macp.v1.ParticipantActivity.Builder addParticipantActivityBuilder(
        int index) {
      return internalGetParticipantActivityFieldBuilder().addBuilder(
          index, io.macp.proto.macp.v1.ParticipantActivity.getDefaultInstance());
    }
    /**
     * <code>repeated .macp.v1.ParticipantActivity participant_activity = 10 [json_name = "participantActivity"];</code>
     */
    public java.util.List<io.macp.proto.macp.v1.ParticipantActivity.Builder> 
         getParticipantActivityBuilderList() {
      return internalGetParticipantActivityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.macp.proto.macp.v1.ParticipantActivity, io.macp.proto.macp.v1.ParticipantActivity.Builder, io.macp.proto.macp.v1.ParticipantActivityOrBuilder> 
        internalGetParticipantActivityFieldBuilder() {
      if (participantActivityBuilder_ == null) {
        participantActivityBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.macp.proto.macp.v1.ParticipantActivity, io.macp.proto.macp.v1.ParticipantActivity.Builder, io.macp.proto.macp.v1.ParticipantActivityOrBuilder>(
                participantActivity_,
                ((bitField0_ & 0x00000200) != 0),
                getParentForChildren(),
                isClean());
        participantActivity_ = null;
      }
      return participantActivityBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:macp.v1.SessionMetadata)
  }

  // @@protoc_insertion_point(class_scope:macp.v1.SessionMetadata)
  private static final io.macp.proto.macp.v1.SessionMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.macp.proto.macp.v1.SessionMetadata();
  }

  public static io.macp.proto.macp.v1.SessionMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionMetadata>
      PARSER = new com.google.protobuf.AbstractParser<SessionMetadata>() {
    @java.lang.Override
    public SessionMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SessionMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.macp.proto.macp.v1.SessionMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

