// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: macp/v1/policy.proto
// Protobuf Java Version: 4.34.1

package io.macp.proto.macp.v1;

@com.google.protobuf.Generated
public interface UnregisterPolicyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:macp.v1.UnregisterPolicyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string policy_id = 1 [json_name = "policyId"];</code>
   * @return The policyId.
   */
  java.lang.String getPolicyId();
  /**
   * <code>string policy_id = 1 [json_name = "policyId"];</code>
   * @return The bytes for policyId.
   */
  com.google.protobuf.ByteString
      getPolicyIdBytes();
}
